 export type CategoryConfig = {
  icon: string;
  subcategories: Record<string, string[]>;
};

export const CATEGORY_CONFIG: Record<string, CategoryConfig> = {
  Electronics: {
    icon: '📱',
    subcategories: {
      Phones: [
        'iPhone',
        'Samsung',
        'Xiaomi',
        'Redmi',
        'Tecno',
        'Infinix',
        'Huawei',
        'Oppo',
        'Other',
      ],
      Computers: [
        'Apple',
        'HP',
        'Dell',
        'Lenovo',
        'Samsung',
        'Asus',
        'Acer',
        'Other',
      ],
      Tablets: [
        'Samsung',
        'Apple',
        'Lenovo',
        'Huawei',
        'Xiaomi',
        'Honor',
        'Amazon',
        'Microsoft',
        'Other',
      ],
      TV: [
        'Samsung',
        'LG',
        'Hisense',
        'TCL',
        'Sony',
        'Skyworth',
        'Toshiba',
        'Xiaomi',
        'Other',
      ],
      Cameras: [
        'Canon',
        'Sony',
        'Nikon',
        'Fujifilm',
        'Panasonic',
        'Olympus',
        'GoPro',
        'DJI',
        'Other',
      ],
      Gaming: [
        'PlayStation',
        'Xbox',
        'Nintendo',
        'Other',
      ],
      Freezer: [
        'Samsung',
        'LG',
        'Hisense',
        'Haier',
        'Midea',
        'Whirlpool',
        'Other',
      ],
      Watch: [
        'Casio',
        'Rolex',
        'Seiko',
        'Citizen',
        'Fossil',
        'Tissot',
        'Apple',
        'Samsung',
        'Other',
      ],
      // Rarely used / related items grouped in one place.
      // These show as the row at the top (like Jiji).
      Accessories: [
        'Photo & Video',
        'TV & DVD',
        'Audio & Microphone',
        'Networking',
        'Printers & Scanners',
        'Game Accessories',
        'Security & Surveillance',
        'Charger',
        'Headphones',
        'Smartwatch',
        'Other accessories',
      ],
    },
  },

  'Vehicles': {
    icon: '🚗',
    subcategories: {
      Cars: [
        'Toyota',
        'Hyundai',
        'Suzuki',
        'BYD',
        'Nissan',
        'Honda',
        'Kia',
        'Mitsubishi',
        'Other',
      ],
      'Pickup Trucks': [
        'Toyota',
        'Ford',
        'Isuzu',
        'Nissan',
        'Mitsubishi',
        'Great Wall',
        'JAC',
        'Foton',
        'Other',
      ],
      'Vans & Minivans': [
        'Toyota',
        'Hyundai',
        'Kia',
        'Nissan',
        'Other',
      ],
      Minibuses: [
        'Toyota',
        'Hyundai',
        'Isuzu',
        'Foton',
        'Other',
      ],
      Buses: [
        'Isuzu',
        'Higer',
        'Yutong',
        'Mercedes-Benz',
        'Hyundai',
        'King Long',
        'Other',
      ],
      Trucks: [
        'Isuzu',
        'Hino',
        'Fuso',
        'Volvo',
        'Scania',
        'Mercedes-Benz',
        'Sinotruk',
        'FAW',
        'Other',
      ],
      Motorcycles: [
        'Honda',
        'Yamaha',
        'Suzuki',
        'Bajaj',
        'TVS',
        'BMW',
        'KTM',
        'Kawasaki',
        'Other',
      ],
      'Three-Wheelers': [
        'Bajaj',
        'TVS',
        'Piaggio',
        'Other',
      ],
      Bicycles: [
        'Mountain Bike',
        'Road Bike',
        'BMX',
        'Electric Bike',
        'City Bike',
        'Kids Bike',
        'Other',
      ],
      'Tractors & Agricultural Vehicles': [
        'Massey Ferguson',
        'John Deere',
        'New Holland',
        'Kubota',
        'Mahindra',
        'Sonalika',
        'Other',
      ],
      'Heavy Machinery': [
        'Excavators',
        'Loaders',
        'Bulldozers',
        'Graders',
        'Cranes',
        'Rollers',
        'Forklifts',
        'Other',
      ],
      'Parts & Accessories': [
        'Engines',
        'Gearboxes',
        'Tires',
        'Wheels/Rims',
        'Batteries',
        'Lights',
        'Body Parts',
        'Brakes',
        'Suspension',
        'Electrical Parts',
        'Interior Parts',
        'Audio',
        'Other',
      ],
      'Other Vehicles': [],
    },
  },

  'Home & Living': {
    icon: '🛋️',
    subcategories: {
      Furniture: [
        'Sofa',
        'Bed',
        'Mattress',
        'Wardrobe',
        'Table',
        'Chair',
        'Dining Set',
        'TV Stand',
        'Desk',
        'Shelf',
        'Cabinet',
        'Other',
      ],
      Refrigerators: [
        'Samsung',
        'LG',
        'Hisense',
        'Haier',
        'Midea',
        'Whirlpool',
        'Beko',
        'Other',
      ],
      'Washing Machines': [
        'Samsung',
        'LG',
        'Hisense',
        'Haier',
        'Midea',
        'Whirlpool',
        'Beko',
        'Other',
      ],
      'Air Conditioners': [
        'Samsung',
        'LG',
        'Midea',
        'Hisense',
        'Gree',
        'Daikin',
        'Carrier',
        'Other',
      ],
      'Kitchen Appliances': [
        'Microwave',
        'Oven',
        'Electric Stove',
        'Gas Stove',
        'Blender',
        'Mixer',
        'Coffee Machine',
        'Air Fryer',
        'Rice Cooker',
        'Electric Kettle',
        'Other',
      ],
      'Home Decor': [
        'Curtains',
        'Carpets',
        'Mirrors',
        'Wall Decor',
        'Clocks',
        'Vases',
        'Lamps',
        'Other',
      ],
    },
  },

  'Fashion': {
    icon: '👗',
    subcategories: {
      "Men's Clothing": [
        'T-Shirts',
        'Shirts',
        'Trousers',
        'Jeans',
        'Jackets',
        'Suits',
        'Sweaters',
        'Traditional Clothing',
        'Sportswear',
        'Other',
      ],
      "Women's Clothing": [
        'Dresses',
        'Tops',
        'Skirts',
        'Jeans',
        'Trousers',
        'Jackets',
        'Traditional Clothing',
        'Hijabs',
        'Sportswear',
        'Other',
      ],
      Shoes: [
        'Sneakers',
        'Formal Shoes',
        'Boots',
        'Sandals',
        'Heels',
        'Slippers',
        'Kids Shoes',
        'Sports Shoes',
        'Other',
      ],
      'Bags & Accessories': [
        'Handbags',
        'Backpacks',
        'Laptop Bags',
        'Travel Bags',
        'School Bags',
        'Wallets',
        'Other',
      ],
      Jewelry: [
        'Rings',
        'Necklaces',
        'Bracelets',
        'Earrings',
        'Gold',
        'Silver',
        'Other',
      ],
      'Other Fashion': [],
    },
  },

  'Beauty & Personal Care': {
    icon: '💄',
    subcategories: {
      Skincare: [],
      Makeup: [],
      'Hair Care': [],
      'Hair Tools': [],
      'Perfumes & Fragrances': [],
      'Shaving & Grooming': [],
      'Oral Care': [],
      'Beauty Equipment': [],
      'Other Beauty': [],
    },
  },

  'Baby & Kids': {
    icon: '👶',
    subcategories: {
      'Baby Clothing': [],
      'Baby Shoes': [],
      Strollers: [],
      'Baby Car Seats': [],
      'Cribs & Baby Furniture': [],
      'Feeding Equipment': [],
      Toys: [],
      'Kids Bicycles': [],
      'School Bags': [],
      'Kids Electronics': [],
      'Other Baby & Kids': [],
    },
  },

  'Tools & Hardware': {
    icon: '🔧',
    subcategories: {
      'Power Tools': [
        'Bosch',
        'Makita',
        'DeWalt',
        'Milwaukee',
        'Stanley',
        'Total',
        'Ingco',
        'Black+Decker',
        'Other',
      ],
      'Hand Tools': [
        'Drills',
        'Hammers',
        'Screwdrivers',
        'Wrenches',
        'Pliers',
        'Saws',
        'Tool Sets',
        'Other',
      ],
      'Welding Equipment': [
        'Welding Machines',
        'Inverters',
        'Welding Accessories',
        'Other',
      ],
      Generators: [
        'Honda',
        'Yamaha',
        'Perkins',
        'Cummins',
        'Caterpillar',
        'Firman',
        'Other',
      ],
    },
  },

  'Agriculture': {
    icon: '🌾',
    subcategories: {
      'Agricultural Machinery': [
        'Tractors',
        'Plows',
        'Harrows',
        'Seeders',
        'Harvesters',
        'Threshers',
        'Cultivators',
        'Sprayers',
        'Irrigation Equipment',
        'Other',
      ],
      'Farm Equipment': [
        'Water Pumps',
        'Sprayers',
        'Milking Equipment',
        'Feeders',
        'Incubators',
        'Greenhouse Equipment',
        'Other',
      ],
      'Agricultural Products': [
        'Seeds',
        'Fertilizers',
        'Animal Feed',
        'Pesticides',
        'Farm Supplies',
        'Other',
      ],
    },
  },

  'Construction & Building': {
    icon: '🏗️',
    subcategories: {
      'Building Materials': [
        'Cement',
        'Sand',
        'Gravel',
        'Bricks',
        'Blocks',
        'Steel',
        'Rebar',
        'Wood',
        'Roofing',
        'Tiles',
        'Paint',
        'Other',
      ],
      Plumbing: [
        'Pipes',
        'Fittings',
        'Water Tanks',
        'Pumps',
        'Bathroom Fixtures',
        'Toilets',
        'Sinks',
        'Showers',
        'Other',
      ],
      'Electrical Materials': [
        'Cables',
        'Switches',
        'Sockets',
        'Breakers',
        'Distribution Boards',
        'Lights',
        'Electrical Accessories',
        'Other',
      ],
      'Construction Machinery': [
        'Excavators',
        'Loaders',
        'Bulldozers',
        'Cranes',
        'Concrete Mixers',
        'Compactors',
        'Compressors',
        'Other',
      ],
    },
  },

  'Office & Business': {
    icon: '💼',
    subcategories: {
      'Office Furniture': [],
      Photocopiers: [],
      Projectors: [],
      'POS & Cash Registers': [],
      Safes: [],
      Shredders: [],
      'Office Supplies': [],
      'Packaging Equipment': [],
      'Commercial Equipment': [],
    },
  },

  'Sports & Fitness': {
    icon: '⚽',
    subcategories: {
      'Gym Equipment': [],
      Treadmills: [],
      'Exercise Bikes': [],
      'Dumbbells & Weights': [],
      Football: [],
      Basketball: [],
      Volleyball: [],
      Tennis: [],
      Running: [],
      Cycling: [],
      'Camping & Outdoor': [],
      Sportswear: [],
      'Other Sports': [],
    },
  },

  'Books & Education': {
    icon: '📚',
    subcategories: {
      Textbooks: [],
      'University Books': [],
      'Medical Books': [],
      'School Books': [],
      "Children's Books": [],
      'Reference Books': [],
      'Religious Books': [],
      Stationery: [],
      'Educational Equipment': [],
      'Other Books': [],
    },
  },

  'Property': {
    icon: '🏠',
    subcategories: {
      'For Rent': [],
      'For Sale': [],
      Land: [],
      Commercial: [],
      'Other Property': [],
    },
  },

  'Jobs & Services': {
    icon: '🛠️',
    subcategories: {
      Jobs: [
        'Full-Time',
        'Part-Time',
        'Contract',
        'Freelance',
        'Internship',
      ],
      Services: [
        'Construction',
        'Electrical',
        'Plumbing',
        'Car Repair',
        'Phone Repair',
        'Computer Repair',
        'Cleaning',
        'Transportation',
        'Delivery',
        'Photography',
        'Graphic Design',
        'Web Development',
        'Tutoring',
        'Translation',
        'Other Services',
      ],
    },
  },

  'Animals & Pets': {
    icon: '🐄',
    subcategories: {
      Cattle: [],
      Sheep: [],
      Goats: [],
      Horses: [],
      Camels: [],
      Chickens: [],
      Birds: [],
      Dogs: [],
      Cats: [],
      Fish: [],
      'Other Pets': [],
      'Animal Equipment': [],
      'Animal Feed': [],
    },
  },

  'Food & Groceries': {
    icon: '🛒',
    subcategories: {
      Grains: [],
      Fruits: [],
      Vegetables: [],
      Meat: [],
      Dairy: [],
      Eggs: [],
      Coffee: [],
      Spices: [],
      'Cooking Oil': [],
      'Packaged Food': [],
      Drinks: [],
      Snacks: [],
      'Other Food': [],
    },
  },

  'Travel & Luggage': {
    icon: '🧳',
    subcategories: {
      Suitcases: [],
      'Travel Bags': [],
      Backpacks: [],
      'Travel Accessories': [],
      'Camping Equipment': [],
      Tents: [],
      'Sleeping Bags': [],
      'Other Travel': [],
    },
  },

  'Hobbies & Collectibles': {
    icon: '🎨',
    subcategories: {
      Collectibles: [],
      Antiques: [],
      Art: [],
      'Musical Instruments': [],
      Photography: [],
      Crafts: [],
      'Coins & Stamps': [],
      'Other Hobbies': [],
    },
  },

  Other: {
    icon: '📦',
    subcategories: {},
  },
};

export const ETHIOPIA_REGIONS = [
  'Addis Ababa',
  'Oromia',
  'Amhara',
  'Tigray',
  'Somali',
  'Afar',
  'Sidama',
  'South Ethiopia',
  'South West Ethiopia',
  'Central Ethiopia',
  'Benishangul-Gumuz',
  'Gambela',
  'Harari',
  'Dire Dawa',
];

export const CONDITIONS = [
  'New',
  'Used - Like New',
  'Used - Good',
  'Used - Fair',
];

// ---------- Brands shown under "Other" ----------
// When the buyer/seller taps "Other", show this list.

export const OTHER_BRANDS: Record<string, string[]> = {
  'Cars': [
    'Volkswagen',
    'Mercedes-Benz',
    'BMW',
    'Lexus',
    'Ford',
    'Chevrolet',
    'Mazda',
    'Subaru',
    'Audi',
    'Land Rover',
    'Jeep',
    'Peugeot',
    'Renault',
    'Chery',
    'Changan',
    'Geely',
    'Jetour',
    'GAC',
    'Great Wall',
    'Haval',
    'Isuzu',
    'Lifan',
    'MG',
    'Volvo',
    'Tesla',
    'Other',
  ],
  'Trucks': [
    'Howo',
    'Shacman',
    'Other',
  ],
  'Motorcycles': [
    'Hero',
    'Lifan',
    'Other',
  ],
  Phones: [
    'Itel',
    'Nokia',
    'Vivo',
    'Honor',
    'Realme',
    'OnePlus',
    'Google',
    'Motorola',
    'Sony',
    'ZTE',
    'Nothing',
    'Poco',
    'Asus',
    'Lenovo',
    'TCL',
    'Other',
  ],
  Tablets: [
    'Tecno',
    'OnePlus',
    'Oppo',
    'Realme',
    'TCL',
    'Asus',
    'Google',
    'Nokia',
    'Motorola',
    'itel',
    'Acer',
    'Alcatel',
    'ZTE',
    'Vivo',
    'Cidea',
    'Other',
  ],
  TV: [
    'Vizio',
    'Westinghouse',
    'Supersonic',
    'Tornado',
    'Vtex',
    'Weyon',
    'Wyinix',
    'Westpool',
    'Vivibright',
    'UKA',
    'TSTV',
    'Tiger',
    'THTF',
    'Televes',
    'Strong',
    'StarTimes',
    'SPJ',
    'SPAK',
    'Sonix',
    'Solstar',
    'Zum',
    'ZEG',
    'Yayi',
    'XGA',
    'Other',
  ],
  Cameras: [
    'Lumix',
    'Pentax',
    'Leica',
    'Kodak',
    'Polaroid',
    'Konica Minolta',
    'Yashica',
    'Hasselblad',
    'Sigma',
    'Yongnuo',
    'Vivitar',
    'JVC',
    'Sanyo',
    'Hitachi',
    'Garmin',
    'Epson',
    'Autel',
    'Syma',
    'Upair',
    'Red5',
    'Sandisk',
    'Xiaomi',
    'Samsung',
    'Other',
  ],
};

// ---------- Tablets: brands and models ----------
// Models are listed once; Wi-Fi/5G, RAM and storage are variants (separate fields).

export const TABLET_BRANDS = [
  'Samsung',
  'Apple',
  'Lenovo',
  'Huawei',
  'Xiaomi',
  'Honor',
  'Amazon',
  'Microsoft',
  'Other',
];

export const TABLET_OTHER_BRANDS = [
  'Tecno',
  'OnePlus',
  'Oppo',
  'Realme',
  'TCL',
  'Asus',
  'Google',
  'Nokia',
  'Motorola',
  'itel',
  'Acer',
  'Alcatel',
  'ZTE',
  'Vivo',
  'Cidea',
  'Other',
];

export const TABLET_MODELS: Record<string, string[]> = {
  Samsung: [
    'Galaxy Tab S12 Ultra',
    'Galaxy Tab S12+',
    'Galaxy Tab S11 Ultra',
    'Galaxy Tab S11',
    'Galaxy Tab S10 Ultra',
    'Galaxy Tab S10+',
    'Galaxy Tab S10 FE+',
    'Galaxy Tab S10 FE',
    'Galaxy Tab S9 Ultra',
    'Galaxy Tab S9+',
    'Galaxy Tab S9',
    'Galaxy Tab S9 FE+',
    'Galaxy Tab S9 FE',
    'Galaxy Tab S8 Ultra',
    'Galaxy Tab S8+',
    'Galaxy Tab S8',
    'Galaxy Tab S7+',
    'Galaxy Tab S7',
    'Galaxy Tab S7 FE',
    'Galaxy Tab S6',
    'Galaxy Tab S6 Lite',
    'Galaxy Tab S5e',
    'Galaxy Tab S4',
    'Galaxy Tab S3',
    'Galaxy Tab S2',
    'Galaxy Tab A11+',
    'Galaxy Tab A11',
    'Galaxy Tab A9+',
    'Galaxy Tab A9',
    'Galaxy Tab A8',
    'Galaxy Tab A7',
    'Galaxy Tab A7 Lite',
    'Galaxy Tab A 10.1',
    'Galaxy Tab A 8.0',
    'Galaxy Tab A 8.4',
    'Galaxy Tab A 10.5',
    'Galaxy Tab A 7.0',
    'Galaxy Tab Active5',
    'Galaxy Tab Active4 Pro',
    'Galaxy Tab Active3',
    'Galaxy Tab Active2',
    'Galaxy View',
    'Galaxy View2',
    'Other',
  ],
  Apple: [
    'iPad (A16)',
    'iPad 10th generation',
    'iPad 9th generation',
    'iPad 8th generation',
    'iPad 7th generation',
    'iPad 6th generation',
    'iPad 5th generation',
    'iPad 4th generation',
    'iPad 3rd generation',
    'iPad 2',
    'iPad',
    'iPad Air 13-inch (M4)',
    'iPad Air 11-inch (M4)',
    'iPad Air 13-inch (M3)',
    'iPad Air 11-inch (M3)',
    'iPad Air 13-inch (M2)',
    'iPad Air 11-inch (M2)',
    'iPad Air 5',
    'iPad Air 4',
    'iPad Air 3',
    'iPad Air 2',
    'iPad Air',
    'iPad Pro 13-inch (M5)',
    'iPad Pro 11-inch (M5)',
    'iPad Pro 13-inch (M4)',
    'iPad Pro 11-inch (M4)',
    'iPad Pro 12.9-inch (6th generation)',
    'iPad Pro 11-inch (4th generation)',
    'iPad Pro 12.9-inch (5th generation)',
    'iPad Pro 11-inch (3rd generation)',
    'iPad Pro 12.9-inch (4th generation)',
    'iPad Pro 11-inch (2nd generation)',
    'iPad Pro 12.9-inch (3rd generation)',
    'iPad Pro 11-inch',
    'iPad Pro 12.9-inch',
    'iPad Pro 10.5-inch',
    'iPad Pro 9.7-inch',
    'iPad mini (A17 Pro)',
    'iPad mini 6',
    'iPad mini 5',
    'iPad mini 4',
    'iPad mini 3',
    'iPad mini 2',
    'iPad mini',
    'Other',
  ],
  Lenovo: [
    'Lenovo Idea Tab',
    'Lenovo Idea Tab Pro',
    'Lenovo Idea Tab Plus',
    'Lenovo Tab',
    'Lenovo Tab One',
    'Lenovo Tab K9',
    'Lenovo Tab K11',
    'Lenovo Tab K11 Gen 2',
    'Lenovo Tab M8',
    'Lenovo Tab M9',
    'Lenovo Tab M10',
    'Lenovo Tab M10 Plus',
    'Lenovo Tab M11',
    'Lenovo Tab P11',
    'Lenovo Tab P11 Plus',
    'Lenovo Tab P11 Pro',
    'Lenovo Tab P12',
    'Lenovo Tab P12 Pro',
    'Lenovo Tab Extreme',
    'Lenovo Yoga Tab 11',
    'Lenovo Yoga Tab 13',
    'Lenovo Yoga Tab Plus',
    'Lenovo Yoga Smart Tab',
    'Lenovo Legion Tab',
    'Lenovo Legion Y700',
    'Lenovo Legion Y700 2023',
    'Lenovo Legion Y700 2025',
    'Lenovo Legion Y700 Gen 4',
    'Lenovo Legion Y700 Gen 5',
    'Other',
  ],
  Huawei: [
    'MatePad',
    'MatePad SE',
    'MatePad SE 10.4',
    'MatePad SE 11',
    'MatePad 10.4',
    'MatePad 11',
    'MatePad 11.5',
    'MatePad 11.5 2025',
    'MatePad 11.5 S',
    'MatePad 11.5 S 2025',
    'MatePad 12 X',
    'MatePad 12 X 2025',
    'MatePad Air',
    'MatePad Air 2025',
    'MatePad Pro 10.8',
    'MatePad Pro 11',
    'MatePad Pro 12.2',
    'MatePad Pro 13.2',
    'MatePad Pro 13.2 2024',
    'MatePad Edge',
    'Other',
  ],
  Xiaomi: [
    'Xiaomi Pad 7',
    'Xiaomi Pad 7 Pro',
    'Xiaomi Pad 7S Pro',
    'Xiaomi Pad 7 Ultra',
    'Xiaomi Pad 6',
    'Xiaomi Pad 6 Pro',
    'Xiaomi Pad 6S Pro',
    'Xiaomi Pad 5',
    'Xiaomi Pad 5 Pro',
    'Xiaomi Pad 5 Pro 12.4',
    'Xiaomi Pad 4',
    'Xiaomi Pad 4 Plus',
    'Xiaomi Pad 3',
    'Xiaomi Pad 2',
    'Xiaomi Pad 1',
    'Redmi Pad',
    'Redmi Pad SE',
    'Redmi Pad SE 8.7',
    'Redmi Pad 2',
    'Redmi Pad 2 SE',
    'Redmi Pad 2 Pro',
    'Redmi Pad Pro',
    'Redmi K Pad',
    'Black Shark Pad',
    'Black Shark Pad 2',
    'Black Shark Pad 5',
    'Black Shark Pad 6',
    'Black Shark Pad 7',
    'Black Shark Pad 7 Pro',
    'Other',
  ],
  Honor: [
    'Honor Pad',
    'Honor Pad X8',
    'Honor Pad X8a',
    'Honor Pad X8b',
    'Honor Pad X9',
    'Honor Pad X9a',
    'Honor Pad X9 Pro',
    'Honor Pad 9',
    'Honor Pad 9 Pro',
    'Honor Pad V7',
    'Honor Pad V8',
    'Honor Pad V9',
    'Honor Pad GT',
    'Honor Pad GT Pro',
    'Honor MagicPad 2',
   'Honor MagicPad 3',
    'Honor MagicPad 3 Pro',
    'Honor MagicPad 4',
    'Other',
  ],
  Amazon: [
    'Fire 7',
    'Fire HD 8',
    'Fire HD 8 Plus',
    'Fire HD 10',
    'Fire HD 10 Plus',
    'Fire Max 11',
    'Fire HD 10 Kids',
    'Fire HD 10 Kids Pro',
    'Fire HD 8 Kids',
    'Fire HD 8 Kids Pro',
    'Other',
  ],
  Microsoft: [
    'Surface Go',
    'Surface Go 2',
    'Surface Go 3',
    'Surface Go 4',
    'Surface Pro',
    'Surface Pro 3',
    'Surface Pro 4',
    'Surface Pro 5',
    'Surface Pro 6',
    'Surface Pro 7',
    'Surface Pro 7+',
    'Surface Pro 8',
    'Surface Pro 9',
    'Surface Pro 10',
    'Surface Pro 11',
    'Surface Pro X',
    'Surface Book',
    'Surface Book 2',
    'Surface Book 3',
    'Other',
  ],
  Tecno: [
    'Tecno MegaPad 10',
    'Tecno MegaPad 11',
    'Tecno MegaPad 12',
    'Tecno MegaPad SE',
    'Tecno MegaPad Pro',
    'Tecno MegaPad 2',
    'Other',
  ],
  OnePlus: [
    'OnePlus Pad',
    'OnePlus Pad Go',
    'OnePlus Pad Go 2',
    'OnePlus Pad 2',
    'OnePlus Pad 3',
    'Other',
  ],
  Oppo: [
    'Oppo Pad',
    'Oppo Pad Air',
    'Oppo Pad 2',
    'Oppo Pad 3',
    'Oppo Pad 3 Pro',
    'Oppo Pad Neo',
    'Oppo Pad SE',
    'Other',
  ],
  Realme: [
    'Realme Pad',
    'Realme Pad Mini',
    'Realme Pad 2',
    'Realme Pad 2 Lite',
    'Realme Pad X',
    'Realme Pad 2 5G',
    'Other',
  ],
  TCL: [
    'TCL Tab 8',
    'TCL Tab 8 LE',
    'TCL Tab 10',
    'TCL Tab 10L',
    'TCL Tab 10s',
    'TCL Tab 10 Gen 2',
    'TCL Tab 11',
    'TCL Tab 11 FE',
    'TCL Tab 12',
    'TCL NXTPAPER 10s',
    'TCL NXTPAPER 11',
    'TCL NXTPAPER 11 Plus',
    'Other',
  ],
  Asus: [
    'ASUS ROG Flow Z13',
    'ASUS ROG Flow Z13 2025',
    'ASUS ROG Tablet',
    'ASUS ZenPad 3S 10',
    'ASUS ZenPad 10',
    'ASUS ZenPad 8',
    'ASUS ZenPad 7',
    'ASUS Transformer Pad',
    'Other',
  ],
  Google: [
    'Google Pixel Tablet',
    'Google Pixel Tablet 2',
    'Other',
  ],
  Nokia: [
    'Nokia T20',
    'Nokia T21',
    'Nokia T10',
    'Nokia T10 LTE',
    'Other',
  ],
  Motorola: [
    'Moto Tab G20',
    'Moto Tab G20 LTE',
    'Moto Tab G62',
    'Moto Tab G70',
    'Moto Tab G70 LTE',
    'Moto Tab G84',
    'Moto Tab 2024',
    'Moto Pad 60',
    'Moto Pad 60 Pro',
    'Moto Pad 70',
    'Moto Pad 2026',
    'Other',
  ],
  itel: [
    'itel Pad 1',
    'itel Pad 2',
    'itel VistaTab 10',
    'itel VistaTab 10 Mini',
    'itel VistaTab 30',
    'itel VistaTab 30 Pro',
    'Other',
  ],
  Acer: [
    'Acer Iconia Tab',
    'Acer Iconia One',
    'Acer Iconia A1',
    'Acer Iconia B1',
    'Acer Iconia W3',
    'Acer Iconia W4',
    'Acer Iconia Tab 10',
    'Acer Iconia Tab 8',
    'Acer Iconia Duo',
    'Other',
  ],
  Alcatel: [
    'Alcatel 1T',
    'Alcatel 1T 7',
    'Alcatel 1T 10',
    'Alcatel 3T 8',
    'Alcatel 3T 10',
    'Alcatel 3T 10 4G',
    'Alcatel Joy Tab',
    'Alcatel Joy Tab 2',
    'Other',
  ],
  ZTE: [
    'ZTE AxonPad',
    'ZTE AxonPad 5G',
    'ZTE nubia Pad 3D',
    'ZTE nubia Pad 3D II',
    'ZTE Red Magic Gaming Tablet',
    'ZTE Blade Tab',
    'ZTE Grand Memo Pad',
    'Other',
  ],
  Vivo: [
    'Vivo Pad',
    'Vivo Pad Air',
    'Vivo Pad2',
    'Vivo Pad3',
    'Vivo Pad3 Pro',
    'Vivo Pad5',
    'Vivo Pad5 Pro',
    'Other',
  ],
  Cidea: ['Other'],
  Other: ['Other'],
};

// ---------- Models: Phones, Computers, Gaming, Watch ----------

export const PHONE_MODELS: Record<string, string[]> = {
  iPhone: [
    'iPhone 17 Pro Max',
    'iPhone 17 Pro',
    'iPhone Air',
    'iPhone 17',
    'iPhone 16e',
    'iPhone 16 Pro Max',
    'iPhone 16 Pro',
    'iPhone 16 Plus',
    'iPhone 16',
    'iPhone 15 Pro Max',
    'iPhone 15 Pro',
    'iPhone 15 Plus',
    'iPhone 15',
    'iPhone 14 Pro Max',
    'iPhone 14 Pro',
    'iPhone 14 Plus',
    'iPhone 14',
    'iPhone 13 Pro Max',
    'iPhone 13 Pro',
    'iPhone 13',
    'iPhone 13 mini',
    'iPhone 12 Pro Max',
    'iPhone 12 Pro',
    'iPhone 12',
    'iPhone 12 mini',
    'iPhone 11 Pro Max',
    'iPhone 11 Pro',
    'iPhone 11',
    'iPhone XS Max',
    'iPhone XS',
    'iPhone XR',
    'iPhone X',
    'iPhone 8 Plus',
    'iPhone 8',
    'iPhone 7 Plus',
    'iPhone 7',
    'iPhone 6s Plus',
    'iPhone 6s',
    'iPhone 6 Plus',
    'iPhone 6',
    'iPhone 5s',
    'iPhone SE (3rd gen)',
    'iPhone SE (2nd gen)',
    'iPhone SE (1st gen)',
    'Other',
  ],
  Samsung: [
    'Galaxy S25 Ultra',
    'Galaxy S25+',
    'Galaxy S25 Edge',
    'Galaxy S25',
    'Galaxy S25 FE',
    'Galaxy S24 Ultra',
    'Galaxy S24+',
    'Galaxy S24',
    'Galaxy S24 FE',
    'Galaxy S23 Ultra',
    'Galaxy S23+',
    'Galaxy S23',
    'Galaxy S23 FE',
    'Galaxy S22 Ultra',
    'Galaxy S22+',
    'Galaxy S22',
    'Galaxy S21 Ultra',
    'Galaxy S21+',
    'Galaxy S21',
    'Galaxy S21 FE',
    'Galaxy S20 Ultra',
    'Galaxy S20+',
    'Galaxy S20',
    'Galaxy S20 FE',
    'Galaxy S10+',
    'Galaxy S10',
    'Galaxy S10e',
    'Galaxy S9+',
    'Galaxy S9',
    'Galaxy S8+',
    'Galaxy S8',
    'Galaxy Z Fold7',
    'Galaxy Z Flip7',
    'Galaxy Z Fold6',
    'Galaxy Z Flip6',
    'Galaxy Z Fold5',
    'Galaxy Z Flip5',
    'Galaxy Z Fold4',
    'Galaxy Z Flip4',
    'Galaxy Z Fold3',
    'Galaxy Z Flip3',
    'Galaxy Note20 Ultra',
    'Galaxy Note20',
    'Galaxy Note10+',
    'Galaxy Note10',
    'Galaxy Note9',
    'Galaxy Note8',
    'Galaxy A56',
    'Galaxy A36',
    'Galaxy A26',
    'Galaxy A17',
    'Galaxy A16',
    'Galaxy A07',
    'Galaxy A06',
    'Galaxy A55',
    'Galaxy A35',
    'Galaxy A25',
    'Galaxy A15',
    'Galaxy A05s',
    'Galaxy A05',
    'Galaxy A54',
    'Galaxy A34',
    'Galaxy A24',
    'Galaxy A14',
    'Galaxy A04s',
    'Galaxy A04',
    'Galaxy A73',
    'Galaxy A53',
    'Galaxy A33',
    'Galaxy A23',
    'Galaxy A13',
    'Galaxy A03',
    'Galaxy A72',
    'Galaxy A52s',
    'Galaxy A52',
    'Galaxy A32',
    'Galaxy A22',
    'Galaxy A12',
    'Galaxy A02s',
    'Galaxy A02',
    'Galaxy A71',
    'Galaxy A51',
    'Galaxy A31',
    'Galaxy A21s',
    'Galaxy A11',
    'Galaxy A80',
    'Galaxy A70',
    'Galaxy A50',
    'Galaxy A30s',
    'Galaxy A20s',
    'Galaxy A10s',
    'Galaxy M55',
    'Galaxy M35',
    'Galaxy M15',
    'Galaxy M54',
    'Galaxy M34',
    'Galaxy M14',
    'Galaxy M33',
    'Galaxy M23',
    'Galaxy M13',
    'Galaxy M52',
    'Galaxy M32',
    'Galaxy M12',
    'Galaxy M31',
    'Other',
  ],
  Xiaomi: [
    'Xiaomi 15T Pro',
    'Xiaomi 15T',
    'Xiaomi 15 Ultra',
    'Xiaomi 15',
    'Xiaomi 14T Pro',
    'Xiaomi 14T',
    'Xiaomi 14 Ultra',
    'Xiaomi 14',
    'Xiaomi 13T Pro',
    'Xiaomi 13T',
    'Xiaomi 13 Ultra',
    'Xiaomi 13 Pro',
    'Xiaomi 13',
    'Xiaomi 13 Lite',
    'Xiaomi 12T Pro',
    'Xiaomi 12T',
    'Xiaomi 12 Pro',
    'Xiaomi 12',
    'Xiaomi 12 Lite',
    'Xiaomi 11T Pro',
    'Xiaomi 11T',
    'Xiaomi 11 Lite 5G NE',
    'Mi 11 Ultra',
    'Mi 11',
    'Mi 10T Pro',
    'Mi 10T',
    'Mi 10',
    'Mi 9T',
    'Mi 9',
    'Mi 8',
    'Mi Note 10',
    'Mi A3',
    'Mi A2',
    'Xiaomi Mix Flip',
    'Xiaomi Mix Fold 4',
    'Other',
  ],
  Redmi: [
    'Redmi Note 15 Pro+',
    'Redmi Note 15 Pro',
    'Redmi Note 15',
    'Redmi Note 14 Pro+',
    'Redmi Note 14 Pro',
    'Redmi Note 14',
    'Redmi Note 13 Pro+',
    'Redmi Note 13 Pro',
    'Redmi Note 13',
    'Redmi Note 12 Pro+',
    'Redmi Note 12 Pro',
    'Redmi Note 12',
    'Redmi Note 11 Pro+',
    'Redmi Note 11 Pro',
    'Redmi Note 11',
    'Redmi Note 10 Pro',
    'Redmi Note 10S',
    'Redmi Note 10',
    'Redmi Note 9 Pro',
    'Redmi Note 9S',
    'Redmi Note 9',
    'Redmi Note 8 Pro',
    'Redmi Note 8T',
    'Redmi Note 8',
    'Redmi Note 7',
    'Redmi 15C',
    'Redmi 15',
    'Redmi 14C',
    'Redmi 13C',
    'Redmi 13',
    'Redmi 12C',
    'Redmi 12',
    'Redmi 10C',
    'Redmi 10A',
    'Redmi 10',
    'Redmi 9C',
    'Redmi 9A',
    'Redmi 9T',
    'Redmi 9',
    'Redmi 8A',
    'Redmi 8',
    'Redmi A5',
    'Redmi A4',
    'Redmi A3',
    'Redmi A2',
    'Redmi A1',
    'Other',
  ],
  Tecno: [
    'Tecno Spark 40 Pro',
    'Tecno Spark 40',
    'Tecno Spark 40C',
    'Tecno Spark 30 Pro',
    'Tecno Spark 30',
    'Tecno Spark 30C',
    'Tecno Spark 20 Pro+',
    'Tecno Spark 20 Pro',
    'Tecno Spark 20',
    'Tecno Spark 20C',
    'Tecno Spark 10 Pro',
    'Tecno Spark 10',
    'Tecno Spark 10C',
    'Tecno Spark Go 2024',
    'Tecno Spark Go 2023',
    'Tecno Spark 9 Pro',
    'Tecno Spark 9T',
    'Tecno Spark 8 Pro',
    'Tecno Spark 8',
    'Tecno Spark 7',
    'Tecno Camon 40 Pro',
    'Tecno Camon 40',
    'Tecno Camon 30 Premier',
    'Tecno Camon 30 Pro',
    'Tecno Camon 30',
    'Tecno Camon 20 Premier',
    'Tecno Camon 20 Pro',
    'Tecno Camon 20',
    'Tecno Camon 19 Pro',
    'Tecno Camon 19',
    'Tecno Camon 18',
    'Tecno Camon 17 Pro',
    'Tecno Camon 17',
    'Tecno Phantom V Fold2',
    'Tecno Phantom V Flip2',
    'Tecno Phantom V Fold',
    'Tecno Phantom V Flip',
    'Tecno Phantom X2 Pro',
    'Tecno Phantom X2',
    'Tecno Pova 7 Pro',
    'Tecno Pova 7',
    'Tecno Pova 6 Pro',
    'Tecno Pova 6',
    'Tecno Pova 5 Pro',
    'Tecno Pova 5',
    'Tecno Pova 4 Pro',
    'Tecno Pova 4',
    'Tecno Pova 3',
    'Tecno Pova 2',
    'Tecno Pop 9',
    'Tecno Pop 8',
    'Tecno Pop 7',
    'Tecno Pop 6',
    'Tecno Pop 5',
    'Other',
  ],
  Infinix: [
    'Infinix Hot 60 Pro',
    'Infinix Hot 60i',
    'Infinix Hot 50 Pro+',
    'Infinix Hot 50 Pro',
    'Infinix Hot 50i',
    'Infinix Hot 50',
    'Infinix Hot 40 Pro',
    'Infinix Hot 40i',
    'Infinix Hot 40',
    'Infinix Hot 30 Play',
    'Infinix Hot 30i',
    'Infinix Hot 30',
    'Infinix Hot 20',
    'Infinix Hot 20i',
    'Infinix Hot 12',
    'Infinix Hot 11',
    'Infinix Hot 10',
    'Infinix Hot 9',
    'Infinix Note 50 Pro+',
    'Infinix Note 50 Pro',
    'Infinix Note 50s',
    'Infinix Note 50',
    'Infinix Note 40 Pro+',
    'Infinix Note 40 Pro',
    'Infinix Note 40',
    'Infinix Note 30 VIP',
    'Infinix Note 30 Pro',
    'Infinix Note 30',
    'Infinix Note 12 Pro',
    'Infinix Note 12',
    'Infinix Note 11 Pro',
    'Infinix Note 11',
    'Infinix Note 10 Pro',
    'Infinix Note 10',
    'Infinix Zero 40',
    'Infinix Zero 30',
    'Infinix Zero 20',
    'Infinix Zero Ultra',
    'Infinix Zero X Pro',
    'Infinix Zero 8',
    'Infinix Smart 10',
    'Infinix Smart 9',
    'Infinix Smart 8',
    'Infinix Smart 7',
    'Infinix Smart 6',
    'Infinix GT 30 Pro',
    'Infinix GT 30',
    'Infinix GT 20 Pro',
    'Infinix GT 10 Pro',
    'Other',
  ],
  Huawei: [
    'Huawei Pura 80 Ultra',
    'Huawei Pura 80 Pro',
    'Huawei Pura 80',
    'Huawei Pura 70 Ultra',
    'Huawei Pura 70 Pro+',
    'Huawei Pura 70 Pro',
    'Huawei Pura 70',
    'Huawei Mate 70 Pro+',
    'Huawei Mate 70 Pro',
    'Huawei Mate 70',
    'Huawei Mate 60 Pro+',
    'Huawei Mate 60 Pro',
    'Huawei Mate 60',
    'Huawei Mate 50 Pro',
    'Huawei Mate 50',
    'Huawei Mate 40 Pro',
    'Huawei Mate 30 Pro',
    'Huawei Mate X6',
    'Huawei Mate X5',
    'Huawei Mate X3',
    'Huawei Mate XT',
    'Huawei P60 Pro',
    'Huawei P60',
    'Huawei P50 Pro',
    'Huawei P50',
    'Huawei P40 Pro',
    'Huawei P40 Lite',
    'Huawei P40',
    'Huawei P30 Pro',
    'Huawei P30 Lite',
    'Huawei P30',
    'Huawei P20 Pro',
    'Huawei Nova 14',
    'Huawei Nova 13',
    'Huawei Nova 12',
    'Huawei Nova 11',
    'Huawei Nova 10',
    'Huawei Nova 9',
    'Huawei Nova 8',
    'Huawei Nova 7',
    'Huawei Nova 5T',
    'Huawei Nova 3i',
    'Huawei Nova Y91',
    'Huawei Nova Y90',
    'Huawei Nova Y72',
    'Huawei Nova Y71',
    'Huawei Nova Y70',
    'Huawei Nova Y61',
    'Huawei Nova Y60',
    'Huawei Y9 Prime 2019',
    'Huawei Y9s',
    'Huawei Y9a',
    'Huawei Y7a',
    'Huawei Y6p',
    'Huawei Y6s',
    'Huawei Y5p',
    'Other',
  ],
  Oppo: [
    'Oppo Find X8 Ultra',
    'Oppo Find X8 Pro',
    'Oppo Find X8',
    'Oppo Find X7 Ultra',
    'Oppo Find X7',
    'Oppo Find X6 Pro',
    'Oppo Find X5 Pro',
    'Oppo Find N5',
    'Oppo Find N3 Flip',
    'Oppo Find N3',
    'Oppo Find N2 Flip',
    'Oppo Reno14 Pro',
    'Oppo Reno14',
    'Oppo Reno13 Pro',
    'Oppo Reno13',
    'Oppo Reno12 Pro',
    'Oppo Reno12',
    'Oppo Reno11 Pro',
    'Oppo Reno11',
    'Oppo Reno10 Pro+',
    'Oppo Reno10 Pro',
    'Oppo Reno10',
    'Oppo Reno8 Pro',
    'Oppo Reno8',
    'Oppo Reno8 T',
    'Oppo Reno7',
    'Oppo Reno6',
    'Oppo Reno5',
    'Oppo Reno4',
    'Oppo A5 Pro',
    'Oppo A5',
    'Oppo A3 Pro',
    'Oppo A3',
    'Oppo A60',
    'Oppo A58',
    'Oppo A38',
    'Oppo A18',
    'Oppo A17',
    'Oppo A16',
    'Oppo A15',
    'Oppo A98',
    'Oppo A96',
    'Oppo A95',
    'Oppo A94',
    'Oppo A93',
    'Oppo A92',
    'Oppo A79',
    'Oppo A78',
    'Oppo A77',
    'Oppo A74',
    'Oppo A57',
    'Oppo A54',
    'Oppo A53',
    'Other',
  ],
  Itel: [
    'Itel A80',
    'Itel A70',
    'Itel A60s',
    'Itel A60',
    'Itel A50',
    'Itel A05s',
    'Itel A04',
    'Itel P55+',
    'Itel P55',
    'Itel P40+',
    'Itel P40',
    'Itel S25 Ultra',
    'Itel S25',
    'Itel S24',
    'Itel S23+',
    'Itel S23',
    'Itel Vision 5',
    'Itel Vision 3',
    'Itel Vision 1 Pro',
    'Itel Zeno 10',
    'Other',
  ],
  Nokia: [
    'Nokia G60 5G',
    'Nokia G42',
    'Nokia G22',
    'Nokia G21',
    'Nokia G20',
    'Nokia G11',
    'Nokia G10',
    'Nokia C32',
    'Nokia C31',
    'Nokia C30',
    'Nokia C22',
    'Nokia C21',
    'Nokia C20',
    'Nokia C12',
    'Nokia C10',
    'Nokia X30',
    'Nokia X20',
    'Nokia X10',
    'Nokia XR21',
    'Nokia 8.3',
    'Nokia 7.2',
    'Nokia 6.2',
    'Nokia 5.4',
    'Nokia 3.4',
    'Nokia 2.4',
    'Nokia 1.4',
    'Nokia 150',
    'Nokia 130',
    'Nokia 110',
    'Nokia 106',
    'Nokia 105',
    'Nokia 225',
    'Nokia 230',
    'Nokia 3310',
    'Nokia 8210 4G',
    'Nokia 2660 Flip',
    'Nokia 2720 Flip',
    'Nokia 6300 4G',
    'Nokia 5310',
    'Other',
  ],
  Vivo: [
    'Vivo X200 Ultra',
    'Vivo X200 Pro',
    'Vivo X200',
    'Vivo X100 Pro',
    'Vivo X100',
    'Vivo X90 Pro',
    'Vivo X80 Pro',
    'Vivo V60',
    'Vivo V50',
    'Vivo V40',
    'Vivo V30 Pro',
    'Vivo V30',
    'Vivo V29',
    'Vivo V27',
    'Vivo V25',
    'Vivo V23',
    'Vivo V21',
    'Vivo Y400',
    'Vivo Y300',
    'Vivo Y200',
    'Vivo Y100',
    'Vivo Y58',
    'Vivo Y36',
    'Vivo Y28',
    'Vivo Y27',
    'Vivo Y22',
    'Vivo Y21',
    'Vivo Y20',
    'Vivo Y19',
    'Vivo Y17',
    'Vivo Y15',
    'Vivo Y12',
    'Vivo Y11',
    'Vivo Y91',
    'Vivo Y93',
    'Vivo Y95',
    'Vivo Y81',
    'Vivo T4',
    'Vivo T3',
    'Vivo T2',
    'Other',
  ],
  Honor: [
    'Honor Magic7 Pro',
    'Honor Magic7',
    'Honor Magic6 Pro',
    'Honor Magic6 Lite',
    'Honor Magic5 Pro',
    'Honor Magic V5',
    'Honor Magic V3',
    'Honor Magic V2',
    'Honor Magic V Flip',
    'Honor 400 Pro',
    'Honor 400',
    'Honor 400 Lite',
    'Honor 200 Pro',
    'Honor 200',
    'Honor 200 Lite',
    'Honor 90',
    'Honor 90 Lite',
    'Honor 70',
    'Honor 50',
    'Honor X9c',
    'Honor X9b',
    'Honor X9a',
    'Honor X8c',
    'Honor X8b',
    'Honor X8a',
    'Honor X8',
    'Honor X7c',
    'Honor X7b',
    'Honor X7a',
    'Honor X7',
    'Honor X6a',
    'Honor X6',
    'Honor X5 Plus',
    'Honor X5',
    'Other',
  ],
  Realme: [
    'Realme 15 Pro',
    'Realme 15',
    'Realme 14 Pro+',
    'Realme 14 Pro',
    'Realme 14',
    'Realme 13 Pro+',
    'Realme 13 Pro',
    'Realme 13',
    'Realme 12 Pro+',
    'Realme 12 Pro',
    'Realme 12',
    'Realme 11 Pro+',
    'Realme 11 Pro',
    'Realme 11',
    'Realme 10 Pro+',
    'Realme 10 Pro',
    'Realme 10',
    'Realme 9 Pro+',
    'Realme 9 Pro',
    'Realme 9',
    'Realme 8 Pro',
    'Realme 8',
    'Realme 7 Pro',
    'Realme 7',
    'Realme 6 Pro',
    'Realme 6',
    'Realme GT 7 Pro',
    'Realme GT 7',
    'Realme GT 6',
    'Realme GT 5',
    'Realme GT Neo 6',
    'Realme GT 2 Pro',
    'Realme C75',
    'Realme C71',
    'Realme C67',
    'Realme C65',
    'Realme C63',
    'Realme C61',
    'Realme C55',
    'Realme C53',
    'Realme C51',
    'Realme C35',
    'Realme C33',
    'Realme C31',
    'Realme C30s',
    'Realme C25Y',
    'Realme C21Y',
    'Realme C15',
    'Realme C11',
    'Realme C3',
    'Realme Note 60',
    'Realme Note 50',
    'Realme Narzo 80 Pro',
    'Realme Narzo 70 Pro',
    'Realme Narzo 60 Pro',
    'Realme Narzo 50',
    'Realme Narzo 30',
    'Other',
  ],
  OnePlus: [
    'OnePlus 15',
    'OnePlus 13R',
    'OnePlus 13',
    'OnePlus 12R',
    'OnePlus 12',
    'OnePlus 11R',
    'OnePlus 11',
    'OnePlus 10 Pro',
    'OnePlus 10T',
    'OnePlus 10R',
    'OnePlus 9 Pro',
    'OnePlus 9R',
    'OnePlus 9',
    'OnePlus 8T',
    'OnePlus 8 Pro',
    'OnePlus 8',
    'OnePlus 7T',
    'OnePlus 7 Pro',
    'OnePlus 7',
    'OnePlus 6T',
    'OnePlus 6',
    'OnePlus 5T',
    'OnePlus 5',
    'OnePlus Nord 5',
    'OnePlus Nord 4',
    'OnePlus Nord 3',
    'OnePlus Nord 2T',
    'OnePlus Nord 2',
    'OnePlus Nord CE 5',
    'OnePlus Nord CE 4 Lite',
    'OnePlus Nord CE 4',
    'OnePlus Nord CE 3 Lite',
    'OnePlus Nord CE 3',
    'OnePlus Nord N30',
    'OnePlus Nord N20',
    'OnePlus Nord N10',
    'OnePlus Open',
    'OnePlus Ace 5',
    'Other',
  ],
  Google: [
    'Google Pixel 10 Pro XL',
    'Google Pixel 10 Pro Fold',
    'Google Pixel 10 Pro',
    'Google Pixel 10',
    'Google Pixel 9 Pro XL',
    'Google Pixel 9 Pro Fold',
    'Google Pixel 9 Pro',
    'Google Pixel 9a',
    'Google Pixel 9',
    'Google Pixel 8 Pro',
    'Google Pixel 8a',
    'Google Pixel 8',
    'Google Pixel 7 Pro',
    'Google Pixel 7a',
    'Google Pixel 7',
    'Google Pixel 6 Pro',
    'Google Pixel 6a',
    'Google Pixel 6',
    'Google Pixel 5a',
    'Google Pixel 5',
    'Google Pixel 4 XL',
    'Google Pixel 4a',
    'Google Pixel 4',
    'Google Pixel 3a XL',
    'Google Pixel 3a',
    'Google Pixel 3 XL',
    'Google Pixel 3',
    'Google Pixel 2 XL',
    'Google Pixel 2',
    'Google Pixel XL',
    'Google Pixel Fold',
    'Other',
  ],
  Motorola: [
    'Moto G Power 2025',
    'Moto G 5G 2025',
    'Moto G Stylus',
    'Moto G86 Power',
    'Moto G85',
    'Moto G84',
    'Moto G75',
    'Moto G73',
    'Moto G72',
    'Moto G71',
    'Moto G64',
    'Moto G55',
    'Moto G54',
    'Moto G53',
    'Moto G35',
    'Moto G34',
    'Moto G32',
    'Moto G24 Power',
    'Moto G24',
    'Moto G15',
    'Moto G14',
    'Moto G13',
    'Moto G04',
    'Moto G200',
    'Moto G100',
    'Moto G60',
    'Moto G50',
    'Moto G31',
    'Moto G22',
    'Moto G20',
    'Moto G10',
    'Moto E15',
    'Moto E14',
    'Moto E13',
    'Moto E40',
    'Moto E32',
    'Moto E22',
    'Moto E20',
    'Moto E7 Power',
    'Moto E7',
    'Moto E6s',
    'Edge 60 Pro',
    'Edge 60 Fusion',
    'Edge 60',
    'Edge 50 Ultra',
    'Edge 50 Pro',
    'Edge 50 Fusion',
    'Edge 50 Neo',
    'Edge 40 Pro',
    'Edge 40 Neo',
    'Edge 40',
    'Edge 30 Ultra',
    'Edge 30 Pro',
    'Edge 30 Neo',
    'Edge 30',
    'Edge 20 Pro',
    'Edge 20',
    'Razr 60 Ultra',
    'Razr 60',
    'Razr 50 Ultra',
    'Razr 50',
    'Razr 40 Ultra',
    'Razr 40',
    'ThinkPhone',
    'Other',
  ],
  Sony: [
    'Sony Xperia 1 VII',
    'Sony Xperia 1 VI',
    'Sony Xperia 1 V',
    'Sony Xperia 1 IV',
    'Sony Xperia 1 III',
    'Sony Xperia 1 II',
    'Sony Xperia 1',
    'Sony Xperia 5 V',
    'Sony Xperia 5 IV',
    'Sony Xperia 5 III',
    'Sony Xperia 5 II',
    'Sony Xperia 5',
    'Sony Xperia 10 VII',
    'Sony Xperia 10 VI',
    'Sony Xperia 10 V',
    'Sony Xperia 10 IV',
    'Sony Xperia 10 III',
    'Sony Xperia 10 II',
    'Sony Xperia 10',
    'Sony Xperia Pro-I',
    'Sony Xperia XZ3',
    'Sony Xperia XZ2',
    'Sony Xperia XZ1',
    'Sony Xperia XZ Premium',
    'Sony Xperia XA2',
    'Other',
  ],
  ZTE: [
    'ZTE Blade A75',
    'ZTE Blade A73',
    'ZTE Blade A72',
    'ZTE Blade A55',
    'ZTE Blade A54',
    'ZTE Blade A53',
    'ZTE Blade A35',
    'ZTE Blade V70',
    'ZTE Blade V60',
    'ZTE Blade V50',
    'ZTE Blade V40 Vita',
    'ZTE Blade V30',
    'ZTE Blade V2020',
    'ZTE Blade V10',
    'ZTE Blade A7s',
    'ZTE Blade A51',
    'ZTE Blade A31',
    'ZTE Axon 60 Ultra',
    'ZTE Axon 50 Ultra',
    'ZTE Axon 40 Ultra',
    'ZTE Axon 30 Ultra',
    'ZTE Axon 30',
    'ZTE Axon 20',
    'nubia Z70 Ultra',
    'nubia Z60 Ultra',
    'nubia Z50 Ultra',
    'nubia Neo 3',
    'nubia Flip 2',
    'nubia Focus Pro',
    'Red Magic 10 Pro',
    'Red Magic 9 Pro',
    'Red Magic 8S Pro',
    'Red Magic 8 Pro',
    'Red Magic 7',
    'Other',
  ],
  Nothing: [
    'Nothing Phone (3)',
    'Nothing Phone (3a) Pro',
    'Nothing Phone (3a)',
    'Nothing Phone (2a) Plus',
    'Nothing Phone (2a)',
    'Nothing Phone (2)',
    'Nothing Phone (1)',
    'CMF Phone 2 Pro',
    'CMF Phone 1',
    'Other',
  ],
  Poco: [
    'Poco F7 Ultra',
    'Poco F7 Pro',
    'Poco F7',
    'Poco F6 Pro',
    'Poco F6',
    'Poco F5 Pro',
    'Poco F5',
    'Poco F4 GT',
    'Poco F4',
    'Poco F3 GT',
    'Poco F3',
    'Poco F2 Pro',
    'Poco X7 Pro',
    'Poco X7',
    'Poco X6 Pro',
    'Poco X6',
    'Poco X5 Pro',
    'Poco X5',
    'Poco X4 Pro',
    'Poco X4 GT',
    'Poco X3 Pro',
    'Poco X3 NFC',
    'Poco X3',
    'Poco M7 Pro',
    'Poco M7',
    'Poco M6 Pro',
    'Poco M6',
    'Poco M5s',
    'Poco M5',
    'Poco M4 Pro',
    'Poco M4',
    'Poco M3 Pro',
    'Poco M3',
    'Poco C75',
    'Poco C71',
    'Poco C65',
    'Poco C61',
    'Poco C55',
    'Poco C51',
    'Poco C40',
    'Poco C31',
    'Poco C3',
    'Other',
  ],
  Asus: [
    'ROG Phone 9 Pro',
    'ROG Phone 9',
    'ROG Phone 8 Pro',
    'ROG Phone 8',
    'ROG Phone 7 Ultimate',
    'ROG Phone 7',
    'ROG Phone 6 Pro',
    'ROG Phone 6',
    'ROG Phone 5s Pro',
    'ROG Phone 5s',
    'ROG Phone 5',
    'ROG Phone 3',
    'ROG Phone 2',
    'Zenfone 12 Ultra',
    'Zenfone 11 Ultra',
    'Zenfone 10',
    'Zenfone 9',
    'Zenfone 8 Flip',
    'Zenfone 8',
    'Zenfone 7 Pro',
    'Zenfone 7',
    'Zenfone 6',
    'Zenfone 5Z',
    'Zenfone 5',
    'Zenfone Max Pro M2',
    'Zenfone Max Pro M1',
    'Zenfone Max M2',
    'Zenfone Max M1',
    'Other',
  ],
  Lenovo: [
    'Legion Phone Duel 2',
    'Legion Phone Duel',
    'Legion Y90',
    'Legion Y70',
    'K13',
    'K12',
    'K10',
    'K9',
    'K8 Plus',
    'K6 Power',
    'Z6 Pro',
    'Z5s',
    'A7',
    'A6 Note',
    'S5 Pro',
    'Vibe K5',
    'Vibe P1',
    'Other',
  ],
  TCL: [
    'TCL 60 SE',
    'TCL 50 SE',
    'TCL 50 XL NxtPaper',
    'TCL 50 NxtPaper',
    'TCL 40 NxtPaper',
    'TCL 40 SE',
    'TCL 40 R',
    'TCL 30 5G',
    'TCL 30 SE',
    'TCL 30+',
    'TCL 30',
    'TCL 20 Pro 5G',
    'TCL 20 SE',
    'TCL 20 5G',
    'TCL 20',
    'TCL 10 Pro',
    'TCL 10L',
    'TCL 10 Plus',
    'TCL 10 SE',
    'TCL 505',
    'TCL 408',
    'TCL 406',
    'Other',
  ],
  Other: ['Other'],
};

export const COMPUTER_MODELS: Record<string, string[]> = {
  Apple: [
    'MacBook Air 15-inch (M4)',
    'MacBook Air 13-inch (M4)',
    'MacBook Air 15-inch (M3)',
    'MacBook Air 13-inch (M3)',
    'MacBook Air 15-inch (M2)',
    'MacBook Air 13-inch (M2)',
    'MacBook Air (M1)',
    'MacBook Air (Intel)',
    'MacBook Pro 16-inch (M4 Pro/Max)',
    'MacBook Pro 14-inch (M4)',
    'MacBook Pro 16-inch (M3 Pro/Max)',
    'MacBook Pro 14-inch (M3)',
    'MacBook Pro 16-inch (M2 Pro/Max)',
    'MacBook Pro 14-inch (M2 Pro/Max)',
    'MacBook Pro 13-inch (M2)',
    'MacBook Pro 16-inch (M1 Pro/Max)',
    'MacBook Pro 14-inch (M1 Pro/Max)',
    'MacBook Pro 13-inch (M1)',
    'MacBook Pro (Intel)',
    'MacBook (12-inch)',
    'iMac 24-inch (M4)',
    'iMac 24-inch (M3)',
    'iMac 24-inch (M1)',
    'iMac (Intel)',
    'Mac mini (M4)',
    'Mac mini (M2)',
    'Mac mini (M1)',
    'Mac mini (Intel)',
    'Mac Studio',
    'Mac Pro',
    'Other',
  ],
  HP: [
    'HP Pavilion',
    'HP Pavilion x360',
    'HP Envy',
    'HP Envy x360',
    'HP Spectre x360',
    'HP Omen',
    'HP Victus',
    'HP EliteBook',
    'HP ProBook',
    'HP ZBook',
    'HP Elite Dragonfly',
    'HP Stream',
    'HP Chromebook',
    'HP 14',
    'HP 15',
    'HP 250 G9',
    'HP 250 G8',
    'HP 255 G9',
    'HP 255 G8',
    'HP Laptop 15s',
    'HP Laptop 14s',
    'HP All-in-One',
    'HP EliteDesk',
    'HP ProDesk',
    'HP Z Workstation',
    'Other',
  ],
  Dell: [
    'Dell Inspiron 14',
    'Dell Inspiron 15',
    'Dell Inspiron 16',
    'Dell Inspiron 2-in-1',
    'Dell XPS 13',
    'Dell XPS 14',
    'Dell XPS 15',
    'Dell XPS 16',
    'Dell XPS 17',
    'Dell Latitude 3000',
    'Dell Latitude 5000',
    'Dell Latitude 7000',
    'Dell Latitude 9000',
    'Dell Vostro',
    'Dell Precision',
    'Dell Alienware',
    'Dell G15',
    'Dell G16',
    'Dell Chromebook',
    'Dell OptiPlex',
    'Dell Inspiron All-in-One',
    'Other',
  ],
  Lenovo: [
    'ThinkPad X1 Carbon',
    'ThinkPad X1 Yoga',
    'ThinkPad X13',
    'ThinkPad T14',
    'ThinkPad T14s',
    'ThinkPad T15',
    'ThinkPad T480',
    'ThinkPad T490',
    'ThinkPad E14',
    'ThinkPad E15',
    'ThinkPad L14',
    'ThinkPad L15',
    'ThinkPad P1',
    'ThinkPad P14s',
    'ThinkPad P15',
    'ThinkBook 14',
    'ThinkBook 15',
    'ThinkBook 16',
    'IdeaPad 1',
    'IdeaPad 3',
    'IdeaPad 5',
    'IdeaPad Slim 3',
    'IdeaPad Slim 5',
    'IdeaPad Flex 5',
    'IdeaPad Gaming 3',
    'Legion 5',
    'Legion 5 Pro',
    'Legion 7',
    'Legion Slim 5',
    'Legion Pro 7',
    'LOQ',
    'Yoga Slim 7',
    'Yoga 7',
    'Yoga 9i',
    'Yoga Pro 9i',
    'Yoga Book',
    'ThinkCentre',
    'IdeaCentre All-in-One',
    'Chromebook',
    'Other',
  ],
  Samsung: [
    'Galaxy Book5 Pro 360',
    'Galaxy Book5 Pro',
    'Galaxy Book5 360',
    'Galaxy Book4 Ultra',
    'Galaxy Book4 Pro 360',
    'Galaxy Book4 Pro',
    'Galaxy Book4 360',
    'Galaxy Book4',
    'Galaxy Book3 Ultra',
    'Galaxy Book3 Pro 360',
    'Galaxy Book3 Pro',
    'Galaxy Book3 360',
    'Galaxy Book3',
    'Galaxy Book2 Pro 360',
    'Galaxy Book2 Pro',
    'Galaxy Book2',
    'Galaxy Book Flex',
    'Galaxy Book Ion',
    'Galaxy Chromebook',
    'Other',
  ],
  Asus: [
    'Asus VivoBook 14',
    'Asus VivoBook 15',
    'Asus VivoBook 16',
    'Asus VivoBook S14',
    'Asus VivoBook S15',
    'Asus VivoBook Go',
    'Asus ZenBook 14',
    'Asus ZenBook 13',
    'Asus ZenBook Pro',
    'Asus ZenBook Flip',
    'Asus ZenBook Duo',
    'Asus ROG Strix',
    'Asus ROG Zephyrus G14',
    'Asus ROG Zephyrus G16',
    'Asus ROG Flow',
    'Asus TUF Gaming F15',
    'Asus TUF Gaming A15',
    'Asus ExpertBook',
    'Asus Chromebook',
    'Asus Vivo AiO',
    'Other',
  ],
  Acer: [
    'Acer Aspire 3',
    'Acer Aspire 5',
    'Acer Aspire 7',
    'Acer Aspire Go',
    'Acer Swift Go',
    'Acer Swift 3',
    'Acer Swift 5',
    'Acer Swift X',
    'Acer Spin',
    'Acer Nitro 5',
    'Acer Nitro V',
    'Acer Predator Helios',
    'Acer Predator Triton',
    'Acer TravelMate',
    'Acer Extensa',
    'Acer Chromebook',
    'Acer Veriton',
    'Other',
  ],
  Other: ['Other'],
};

export const GAMING_MODELS: Record<string, string[]> = {
  PlayStation: [
    'PlayStation 5 Pro',
    'PlayStation 5 Slim',
    'PlayStation 5 Digital Edition',
    'PlayStation 5',
    'PlayStation 4 Pro',
    'PlayStation 4 Slim',
    'PlayStation 4',
    'PlayStation 3',
    'PlayStation 2',
    'PlayStation Portal',
    'PS VR2',
    'DualSense Controller',
    'DualShock 4 Controller',
    'PS5 Games',
    'PS4 Games',
    'Other',
  ],
  Xbox: [
    'Xbox Series X',
    'Xbox Series S',
    'Xbox One X',
    'Xbox One S',
    'Xbox One',
    'Xbox 360',
    'Xbox Wireless Controller',
    'Xbox Games',
    'Other',
  ],
  Nintendo: [
    'Nintendo Switch 2',
    'Nintendo Switch OLED',
    'Nintendo Switch',
    'Nintendo Switch Lite',
    'Nintendo 3DS XL',
    'Nintendo 3DS',
    'Nintendo 2DS',
    'Nintendo Wii U',
    'Nintendo Wii',
    'Switch Games',
    'Other',
  ],
  Other: ['Other'],
};

export const WATCH_MODELS: Record<string, string[]> = {
  Casio: [
    'G-Shock',
    'G-Shock Mudmaster',
    'G-Shock Gravitymaster',
    'Baby-G',
    'Edifice',
    'Pro Trek',
    'Casio Vintage',
    'Casio Standard',
    'Casio Collection',
    'Casio Sheen',
    'Casio Databank',
    'Other',
  ],
  Rolex: [
    'Submariner',
    'Sea-Dweller',
    'Datejust',
    'Day-Date',
    'Daytona',
    'GMT-Master II',
    'Explorer',
    'Explorer II',
    'Oyster Perpetual',
    'Air-King',
    'Yacht-Master',
    'Sky-Dweller',
    'Milgauss',
    'Other',
  ],
  Seiko: [
    'Seiko 5',
    'Seiko 5 Sports',
    'Prospex',
    'Presage',
    'Astron',
    'Seiko Solar',
    'Seiko Kinetic',
    'Seiko Chronograph',
    'Other',
  ],
  Citizen: [
    'Eco-Drive',
    'Promaster',
    'Tsuyosa',
    'Citizen Automatic',
    'Citizen Chronograph',
    'Citizen Quartz',
    'Other',
  ],
  Fossil: [
    'Fossil Gen 6',
    'Fossil Grant',
    'Fossil Neutra',
    'Fossil Machine',
    'Fossil Townsman',
    'Fossil Jacqueline',
    'Fossil Carlyle',
    'Fossil Hybrid',
    'Other',
  ],
  Tissot: [
    'Tissot PRX',
    'Tissot Gentleman',
    'Tissot Seastar',
    'Tissot Le Locle',
    'Tissot T-Touch',
    'Tissot Heritage',
    'Tissot Supersport',
    'Tissot Everytime',
    'Other',
  ],
  Apple: [
    'Apple Watch Ultra 3',
    'Apple Watch Ultra 2',
    'Apple Watch Ultra',
    'Apple Watch Series 11',
    'Apple Watch Series 10',
    'Apple Watch Series 9',
    'Apple Watch Series 8',
    'Apple Watch Series 7',
    'Apple Watch Series 6',
    'Apple Watch Series 5',
    'Apple Watch Series 4',
    'Apple Watch Series 3',
    'Apple Watch SE (3rd gen)',
    'Apple Watch SE (2nd gen)',
    'Apple Watch SE',
    'Other',
  ],
  Samsung: [
    'Galaxy Watch Ultra',
    'Galaxy Watch8 Classic',
    'Galaxy Watch8',
    'Galaxy Watch7',
    'Galaxy Watch6 Classic',
    'Galaxy Watch6',
    'Galaxy Watch5 Pro',
    'Galaxy Watch5',
    'Galaxy Watch4 Classic',
    'Galaxy Watch4',
    'Galaxy Watch FE',
    'Galaxy Watch3',
    'Galaxy Watch Active2',
    'Galaxy Fit3',
    'Other',
  ],
  Other: ['Other'],
};

// TV "model" = screen size (works for every brand)
export const TV_SIZES = [
  '24 inch',
  '32 inch',
  '40 inch',
  '43 inch',
  '50 inch',
  '55 inch',
  '58 inch',
  '65 inch',
  '70 inch',
  '75 inch',
  '85 inch',
  'Other',
];

// Freezer "model" = type (works for every brand)
export const FREEZER_TYPES = [
  'Chest Freezer',
  'Upright Freezer',
  'Single Door Fridge',
  'Double Door Fridge',
  'Side by Side Fridge',
  'Mini Fridge',
  'Showcase Freezer',
  'Display Fridge',
  'Other',
];

// ---------- Vehicles: models ----------

export const CAR_MODELS: Record<string, string[]> = {
  Toyota: [
    'Corolla',
    'Corolla Cross',
    'Yaris',
    'Vitz',
    'Starlet',
    'Raize',
    'Vios',
    'Auris',
    'Camry',
    'Avensis',
    'Belta',
    'Premio',
    'Allion',
    'Probox',
    'Succeed',
    'Passo',
    'Aqua',
    'Prius',
    'Wish',
    'Ist',
    'RAV4',
    'C-HR',
    'Harrier',
    'Highlander',
    'Rush',
    'Fortuner',
    'Land Cruiser',
    'Land Cruiser Prado',
    'Land Cruiser 70',
    'Hilux',
    'Hiace',
    'Noah',
    'Voxy',
    'Alphard',
    'Sienna',
    'Other',
  ],
  Hyundai: [
    'Tucson',
    'Santa Fe',
    'Palisade',
    'Creta',
    'Kona',
    'Venue',
    'Elantra',
    'Accent',
    'Sonata',
    'Azera',
    'Verna',
    'i10',
    'Grand i10',
    'i20',
    'i30',
    'Atos',
    'Getz',
    'Staria',
    'H-1',
    'County',
    'Ioniq 5',
    'Other',
  ],
  Suzuki: [
    'Dzire',
    'Swift',
    'Alto',
    'Celerio',
    'Baleno',
    'Ciaz',
    'Fronx',
    'Wagon R',
    'Vitara',
    'Grand Vitara',
    'Ertiga',
    'Jimny',
    'S-Presso',
    'Every',
    'APV',
    'Carry',
    'Other',
  ],
  BYD: [
    'Seal',
    'Seal U',
    'Atto 3',
    'Dolphin',
    'Seagull',
    'Qin',
    'Song Plus',
    'Song Pro',
    'Han',
    'Tang',
    'Yuan Plus',
    'Sealion 7',
    'Destroyer 05',
    'e2',
    'e6',
    'Other',
  ],
  Nissan: [
    'Sunny',
    'Almera',
    'Tiida',
    'March',
    'Micra',
    'Note',
    'Juke',
    'Kicks',
    'Qashqai',
    'X-Trail',
    'Murano',
    'Pathfinder',
    'Patrol',
    'Navara',
    'Hardbody',
    'Altima',
    'Sentra',
    'Caravan',
    'Urvan',
    'Leaf',
    'Other',
  ],
  Honda: [
    'Fit',
    'Fit Shuttle',
    'Jazz',
    'City',
    'Civic',
    'Accord',
    'Insight',
    'CR-V',
    'HR-V',
    'Vezel',
    'Pilot',
    'Freed',
    'Stepwgn',
    'Odyssey',
    'N-Box',
    'Other',
  ],
  Kia: [
    'Picanto',
    'Morning',
    'Rio',
    'Cerato',
    'K5',
    'Optima',
    'Soul',
    'Stonic',
    'Sonet',
    'Seltos',
    'Sportage',
    'Sorento',
    'Telluride',
    'Carnival',
    'Niro',
    'EV6',
    'Bongo',
    'Other',
  ],
  Mitsubishi: [
    'Pajero',
    'Montero Sport',
    'L200',
    'Triton',
    'Outlander',
    'ASX',
    'Eclipse Cross',
    'Lancer',
    'Mirage',
    'Xpander',
    'Delica',
    'Other',
  ],
  Volkswagen: [
    'Polo',
    'Golf',
    'Jetta',
    'Passat',
    'Beetle',
    'Tiguan',
    'Touareg',
    'Caddy',
    'Transporter',
    'Amarok',
    'ID.4',
    'Santana',
    'Other',
  ],
  'Mercedes-Benz': [
    'A-Class',
    'C-Class',
    'E-Class',
    'S-Class',
    'CLA',
    'GLA',
    'GLC',
    'GLE',
    'GLS',
    'ML',
    'G-Class',
    'Sprinter',
    'Vito',
    'Other',
  ],
  BMW: [
    '1 Series',
    '3 Series',
    '5 Series',
    '7 Series',
    'X1',
    'X3',
    'X5',
    'X6',
    'i4',
    'iX',
    'Other',
  ],
  Lexus: [
    'IS',
    'ES',
    'LS',
    'UX',
    'NX',
    'RX',
    'GX',
    'LX',
    'Other',
  ],
  Ford: [
    'Fiesta',
    'Focus',
    'Fusion',
    'Mustang',
    'EcoSport',
    'Escape',
    'Territory',
    'Explorer',
    'Everest',
    'Ranger',
    'F-150',
    'Transit',
    'Other',
  ],
  Chevrolet: [
    'Spark',
    'Aveo',
    'Optra',
    'Cruze',
    'Malibu',
    'Captiva',
    'Camaro',
    'Tahoe',
    'Silverado',
    'Other',
  ],
  Mazda: [
    'Demio',
    'Mazda 2',
    'Mazda 3',
    'Mazda 6',
    'CX-3',
    'CX-30',
    'CX-5',
    'CX-9',
    'BT-50',
    'Other',
  ],
  Subaru: [
    'Impreza',
    'Legacy',
    'WRX',
    'XV',
    'Crosstrek',
    'Forester',
    'Outback',
    'Other',
  ],
  Audi: [
    'A1',
    'A3',
    'A4',
    'A6',
    'A8',
    'Q3',
    'Q5',
    'Q7',
    'Other',
  ],
  'Land Rover': [
    'Range Rover',
    'Range Rover Sport',
    'Range Rover Evoque',
    'Range Rover Velar',
    'Discovery',
    'Defender',
    'Freelander',
    'Other',
  ],
  Jeep: [
    'Wrangler',
    'Grand Cherokee',
    'Cherokee',
    'Compass',
    'Renegade',
    'Other',
  ],
  Peugeot: [
    '206',
    '207',
    '301',
    '308',
    '508',
    '3008',
    '5008',
    'Partner',
    'Other',
  ],
  Renault: [
    'Kwid',
    'Clio',
    'Sandero',
    'Logan',
    'Symbol',
    'Megane',
    'Duster',
    'Captur',
    'Other',
  ],
  Chery: [
    'QQ',
    'Arrizo 5',
    'Tiggo 2',
    'Tiggo 4',
    'Tiggo 7',
    'Tiggo 8',
    'Other',
  ],
  Changan: [
    'Alsvin',
    'Eado',
    'CS35',
    'CS55',
    'CS75',
    'Hunter',
    'Uni-T',
    'Uni-K',
    'Other',
  ],
  Geely: [
    'Emgrand',
    'Coolray',
    'Azkarra',
    'Atlas',
    'Okavango',
    'Monjaro',
    'Other',
  ],
  Jetour: [
    'Dashing',
    'X70',
    'X90',
    'T2',
    'Other',
  ],
  GAC: [
    'GA4',
    'GS3',
    'GS8',
    'Emkoo',
    'Other',
  ],
  'Great Wall': [
    'Wingle',
    'Poer',
    'Haval H6',
    'Tank 300',
    'Other',
  ],
  Haval: [
    'Jolion',
    'H6',
    'H9',
    'Dargo',
    'Other',
  ],
  Isuzu: [
    'D-Max',
    'MU-X',
    'NPR',
    'Elf',
    'Other',
  ],
  Lifan: [
    '520',
    '620',
    'Solano',
    'X60',
    'Other',
  ],
  MG: [
    'MG3',
    'MG5',
    'MG6',
    'ZS',
    'HS',
    'RX5',
    'One',
    'Other',
  ],
  Volvo: [
    'S60',
    'S90',
    'V40',
    'XC60',
    'XC90',
    'Other',
  ],
  Tesla: [
    'Model 3',
    'Model S',
    'Model X',
    'Model Y',
    'Other',
  ],
  JAC: [
    'T6',
    'T8',
    'Refine',
    'Other',
  ],
  Foton: [
    'Tunland',
    'View',
    'Toano',
    'Other',
  ],
  Other: ['Other'],
};

export const MOTORCYCLE_MODELS: Record<string, string[]> = {
  Bajaj: [
    'Boxer BM 100',
    'Boxer BM 150',
    'Pulsar 150',
    'Pulsar 180',
    'Pulsar 220F',
    'Pulsar NS200',
    'Discover 125',
    'Platina',
    'CT100',
    'Avenger',
    'Dominar 400',
    'Other',
  ],
  TVS: [
    'Apache RTR 160',
    'Apache RTR 180',
    'Apache RTR 200',
    'HLX 125',
    'HLX 150',
    'Star City',
    'Raider 125',
    'Jupiter',
    'Other',
  ],
  Honda: [
    'CG125',
    'CB125F',
    'CB150',
    'XR150L',
    'CRF250L',
    'Africa Twin',
    'PCX',
    'Wave',
    'Dream',
    'Activa',
    'Other',
  ],
  Yamaha: [
    'YBR125',
    'FZ-S',
    'R15',
    'MT-15',
    'XTZ125',
    'NMAX',
    'Aerox',
    'Crux',
    'Other',
  ],
  Suzuki: [
    'GN125',
    'GS150',
    'GSX-R150',
    'Address',
    'Burgman',
    'Other',
  ],
  Hero: [
    'Splendor',
    'HF Deluxe',
    'Passion',
    'Glamour',
    'Other',
  ],
  Kawasaki: [
    'Ninja 400',
    'Ninja 650',
    'Z650',
    'KLX150',
    'Other',
  ],
  KTM: [
    'Duke 200',
    'Duke 390',
    'RC 200',
    'Other',
  ],
  BMW: [
    'R 1250 GS',
    'G 310 R',
    'S 1000 RR',
    'Other',
  ],
  Other: ['Other'],
};

// ---------- TV & Audio types ----------

export const TV_AUDIO_TYPES = [
  'TVs',
  'Projectors',
  'TV Receivers',
  'Media Players',
  'Decoders',
  'Digital Signage',
  'DVD Players',
  'Speakers',
  'Microphones',
  'Home Theater Systems',
  'Sound Systems',
  'Soundcards',
  'Amplifiers',
  'Music Mixers',
  'Radios',
  'Turntables',
  'Karaoke',
  'Other',
];

// ---------- Cameras: types and models ----------

export const CAMERA_TYPES = [
  'Digital Cameras',
  'DSLR Cameras',
  'Video Cameras',
  'Action Cameras',
  'Film Cameras',
  'Camera Lenses',
  'Drones',
  'Accessories',
];

export const CAMERA_MODELS: Record<string, string[]> = {
  Canon: [
    'EOS 1500D',
    'EOS 2000D',
    'EOS 4000D',
    'EOS 80D',
    'EOS 90D',
    'EOS 5D Mark IV',
    'EOS R',
    'EOS R6',
    'EOS M50',
    'Other',
  ],
  Sony: [
    'Alpha a6000',
    'Alpha a6400',
    'Alpha a7 III',
    'Alpha a7 IV',
    'ZV-E10',
    'ZV-1',
    'Handycam',
    'Other',
  ],
  Nikon: [
    'D3500',
    'D5600',
    'D7500',
    'D850',
    'Z50',
    'Z6 II',
    'Z fc',
    'Other',
  ],
  GoPro: [
    'Hero 9',
    'Hero 10',
    'Hero 11',
    'Hero 12',
    'Other',
  ],
  DJI: [
    'Osmo Action 3',
    'Osmo Pocket 2',
    'Mini 3',
    'Mavic 3',
    'Other',
  ],
  Fujifilm: [
    'X-T30',
    'X-S10',
    'Instax Mini',
    'Other',
  ],
  Panasonic: ['Lumix G7', 'Lumix GH5', 'Lumix S5', 'Other'],
  Lumix: ['G7', 'GH5', 'S5', 'FZ300', 'Other'],
  Olympus: ['OM-D E-M10', 'OM-D E-M5', 'PEN E-PL9', 'Other'],
  Pentax: ['K-70', 'K-3 III', 'KF', 'Other'],
  Leica: ['Q2', 'M10', 'D-Lux 7', 'Other'],
  Kodak: ['PixPro AZ401', 'Ektar H35', 'Other'],
  Polaroid: ['Now', 'OneStep', 'Other'],
  Sigma: ['18-35mm f/1.8', '50mm f/1.4', '24-70mm f/2.8', 'Other'],
  Yongnuo: ['YN50mm f/1.8', 'YN560 Flash', 'Other'],
  Vivitar: ['Other'],
  JVC: ['Other'],
  Xiaomi: ['Mi Action Camera 4K', 'Other'],
  Samsung: ['Other'],
  Other: ['Other'],
};

// ---------- Subcategory pictures ----------
// Pictures live in public/categories/sub/<slug>.jpg
// When you add a new picture, add its slug to this list.

const SUB_IMAGES = new Set([
  'phones',
  'computers-tablets',
  'tv-audio',
  'cameras',
  'gaming',

  'cars',
  'motorcycles',
  'trucks-vans',
  'parts-accessories',

  'sofas',
  'beds',
  'tables-chairs',
  'storage',
  'other-furniture',

  'men-s-clothing',
  'women-s-clothing',
  'shoes',
  'bags-accessories',
  'other-fashion',

  'for-rent',
  'land',
  'other-property',
]);

// "Men's Clothing" -> "men-s-clothing"
export function subcategorySlug(
  name: string,
): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Returns the picture path,
// or null if that subcategory has no picture yet
export function subcategoryImage(
  name: string,
): string | null {
  const raw = subcategorySlug(name);

  // Reuse existing pictures after renaming
  const aliases: Record<string, string> = {
    computers: 'computers-tablets',
    tv: 'tv-audio',
    furniture: 'sofas',
    trucks: 'trucks-vans',
    'pickup-trucks': 'trucks-vans',
    'vans-minivans': 'trucks-vans',
  };

  const slug = aliases[raw] ?? raw;

  return SUB_IMAGES.has(slug)
    ? `/categories/sub/${slug}.jpg`
    : null;
}


// ---------- Helpers ----------

// Models for a subcategory + brand (empty list = no models yet)
export function getModels(
  subcategory: string,
  brand: string,
): string[] {
  switch (subcategory) {
    case 'Phones':
      return PHONE_MODELS[brand] ?? ['Other'];
    case 'Computers':
      return COMPUTER_MODELS[brand] ?? ['Other'];
    case 'Tablets':
      return TABLET_MODELS[brand] ?? ['Other'];
    case 'Cameras':
      return CAMERA_MODELS[brand] ?? ['Other'];
    case 'Gaming':
      return GAMING_MODELS[brand] ?? ['Other'];
    case 'Watch':
      return WATCH_MODELS[brand] ?? ['Other'];
    case 'Cars':
    case 'Pickup Trucks':
    case 'Vans & Minivans':
    case 'Minibuses':
      return CAR_MODELS[brand] ?? ['Other'];
    case 'Motorcycles':
      return MOTORCYCLE_MODELS[brand] ?? ['Other'];
    case 'TV':
      return TV_SIZES;
    case 'Freezer':
      return FREEZER_TYPES;
    default:
      return [];
  }
}

// Extra brands shown after the buyer/seller taps "Other"
export function getOtherBrands(
  subcategory: string,
): string[] {
  return OTHER_BRANDS[subcategory] ?? [];
  }
      
  
