 export type CategoryConfig = {
  icon: string;
  subcategories: Record<string, string[]>;
};

export const CATEGORY_CONFIG: Record<string, CategoryConfig> = {
  Electronics: {
    icon: '📱',
    subcategories: {
      Phones: [
        'iPhone',
        'Samsung',
        'Xiaomi',
        'Redmi',
        'Tecno',
        'Infinix',
        'Huawei',
        'Oppo',
        'Other',
      ],
      Computers: [
        'Apple',
        'HP',
        'Dell',
        'Lenovo',
        'Samsung',
        'Asus',
        'Acer',
        'Other',
      ],
      Tablets: [
        'Samsung',
        'Apple',
        'Lenovo',
        'Huawei',
        'Xiaomi',
        'Honor',
        'Amazon',
        'Microsoft',
        'Other',
      ],
      TV: [
        'Samsung',
        'LG',
        'Hisense',
        'TCL',
        'Sony',
        'Skyworth',
        'Toshiba',
        'Xiaomi',
        'Other',
      ],
      Audio: [
        'JBL',
        'Sony',
        'Samsung',
        'LG',
        'Xiaomi',
        'Anker',
        'Edifier',
        'Akai',
        'Other',
      ],
      Cameras: [
        'Canon',
        'Sony',
        'Nikon',
        'Fujifilm',
        'Panasonic',
        'Olympus',
        'GoPro',
        'DJI',
        'Other',
      ],
      Gaming: [
        'PlayStation',
        'Xbox',
        'Nintendo',
        'Other',
      ],
      Freezer: [
        'Samsung',
        'LG',
        'Hisense',
        'Haier',
        'Midea',
        'Whirlpool',
        'Other',
      ],
      Watch: [
        'Casio',
        'Rolex',
        'Seiko',
        'Citizen',
        'Fossil',
        'Tissot',
        'Apple',
        'Samsung',
        'Other',
      ],
      // Tapping "Other" shows these as the options
      Other: [
        'Charger',
        'Headphones',
        'Smartwatch',
        'Other accessories',
      ],
    },
  },

  Vehicles: {
    icon: '🚗',
    subcategories: {
      Cars: [
        'Toyota',
        'Hyundai',
        'Suzuki',
        'Nissan',
        'Volkswagen',
        'Other',
      ],
      Motorcycles: [
        'Bajaj',
        'TVS',
        'Other',
      ],
      'Trucks & Vans': [],
      'Parts & Accessories': [],
      'Other Vehicles': [],
    },
  },

  Furniture: {
    icon: '🛋️',
    subcategories: {
      Sofas: [],
      Beds: [],
      'Tables & Chairs': [],
      Storage: [],
      'Other Furniture': [],
    },
  },

  Fashion: {
    icon: '👗',
    subcategories: {
      "Men's Clothing": [],
      "Women's Clothing": [],
      Shoes: [],
      'Bags & Accessories': [],
      'Other Fashion': [],
    },
  },

  Property: {
    icon: '🏠',
    subcategories: {
      'For Rent': [],
      'For Sale': [],
      Land: [],
      'Other Property': [],
    },
  },

  Other: {
    icon: '📦',
    subcategories: {},
  },
};

export const ETHIOPIA_REGIONS = [
  'Addis Ababa',
  'Oromia',
  'Amhara',
  'Tigray',
  'Somali',
  'Afar',
  'Sidama',
  'South Ethiopia',
  'South West Ethiopia',
  'Central Ethiopia',
  'Benishangul-Gumuz',
  'Gambela',
  'Harari',
  'Dire Dawa',
];

export const CONDITIONS = [
  'New',
  'Used - Like New',
  'Used - Good',
  'Used - Fair',
];

// ---------- Brands shown under "Other" ----------
// When the buyer/seller taps "Other", show this list.

export const OTHER_BRANDS: Record<string, string[]> = {
  Phones: [
    'Itel',
    'Nokia',
    'Vivo',
    'Honor',
    'Realme',
    'OnePlus',
    'Google',
    'Motorola',
    'Sony',
    'ZTE',
    'Nothing',
    'Poco',
    'Asus',
    'Lenovo',
    'TCL',
    'Other',
  ],
  Tablets: [
    'Tecno',
    'OnePlus',
    'Oppo',
    'Realme',
    'TCL',
    'Asus',
    'Google',
    'Nokia',
    'Motorola',
    'itel',
    'Acer',
    'Alcatel',
    'ZTE',
    'Vivo',
    'Cidea',
    'Other',
  ],
  TV: [
    'Vizio',
    'Westinghouse',
    'Supersonic',
    'Tornado',
    'Vtex',
    'Weyon',
    'Wyinix',
    'Westpool',
    'Vivibright',
    'UKA',
    'TSTV',
    'Tiger',
    'THTF',
    'Televes',
    'Strong',
    'StarTimes',
    'SPJ',
    'SPAK',
    'Sonix',
    'Solstar',
    'Zum',
    'ZEG',
    'Yayi',
    'XGA',
    'Other',
  ],
  Audio: [
    'AKG',
    'Alesis',
    'Alpine',
    'Audio-Technica',
    'Bluesound',
    'Boombest',
    'Cambridge',
    'Creative',
    'Crown',
    'Fender',
    'Focusrite',
    'Hama',
    'Ibanez',
    'Jabra',
    'Other',
  ],
  Cameras: [
    'Lumix',
    'Pentax',
    'Leica',
    'Kodak',
    'Polaroid',
    'Konica Minolta',
    'Yashica',
    'Hasselblad',
    'Sigma',
    'Yongnuo',
    'Vivitar',
    'JVC',
    'Sanyo',
    'Hitachi',
    'Garmin',
    'Epson',
    'Autel',
    'Syma',
    'Upair',
    'Red5',
    'Sandisk',
    'Xiaomi',
    'Samsung',
    'Other',
  ],
};

// ---------- Tablets: brands and models ----------
// Models are listed once; Wi-Fi/5G, RAM and storage are variants (separate fields).

export const TABLET_BRANDS = [
  'Samsung',
  'Apple',
  'Lenovo',
  'Huawei',
  'Xiaomi',
  'Honor',
  'Amazon',
  'Microsoft',
  'Other',
];

export const TABLET_OTHER_BRANDS = [
  'Tecno',
  'OnePlus',
  'Oppo',
  'Realme',
  'TCL',
  'Asus',
  'Google',
  'Nokia',
  'Motorola',
  'itel',
  'Acer',
  'Alcatel',
  'ZTE',
  'Vivo',
  'Cidea',
  'Other',
];

export const TABLET_MODELS: Record<string, string[]> = {
  Samsung: [
    'Galaxy Tab S12 Ultra',
    'Galaxy Tab S12+',
    'Galaxy Tab S11 Ultra',
    'Galaxy Tab S11',
    'Galaxy Tab S10 Ultra',
    'Galaxy Tab S10+',
    'Galaxy Tab S10 FE+',
    'Galaxy Tab S10 FE',
    'Galaxy Tab S9 Ultra',
    'Galaxy Tab S9+',
    'Galaxy Tab S9',
    'Galaxy Tab S9 FE+',
    'Galaxy Tab S9 FE',
    'Galaxy Tab S8 Ultra',
    'Galaxy Tab S8+',
    'Galaxy Tab S8',
    'Galaxy Tab S7+',
    'Galaxy Tab S7',
    'Galaxy Tab S7 FE',
    'Galaxy Tab S6',
    'Galaxy Tab S6 Lite',
    'Galaxy Tab S5e',
    'Galaxy Tab S4',
    'Galaxy Tab S3',
    'Galaxy Tab S2',
    'Galaxy Tab A11+',
    'Galaxy Tab A11',
    'Galaxy Tab A9+',
    'Galaxy Tab A9',
    'Galaxy Tab A8',
    'Galaxy Tab A7',
    'Galaxy Tab A7 Lite',
    'Galaxy Tab A 10.1',
    'Galaxy Tab A 8.0',
    'Galaxy Tab A 8.4',
    'Galaxy Tab A 10.5',
    'Galaxy Tab A 7.0',
    'Galaxy Tab Active5',
    'Galaxy Tab Active4 Pro',
    'Galaxy Tab Active3',
    'Galaxy Tab Active2',
    'Galaxy View',
    'Galaxy View2',
    'Other',
  ],
  Apple: [
    'iPad (A16)',
    'iPad 10th generation',
    'iPad 9th generation',
    'iPad 8th generation',
    'iPad 7th generation',
    'iPad 6th generation',
    'iPad 5th generation',
    'iPad 4th generation',
    'iPad 3rd generation',
    'iPad 2',
    'iPad',
    'iPad Air 13-inch (M4)',
    'iPad Air 11-inch (M4)',
    'iPad Air 13-inch (M3)',
    'iPad Air 11-inch (M3)',
    'iPad Air 13-inch (M2)',
    'iPad Air 11-inch (M2)',
    'iPad Air 5',
    'iPad Air 4',
    'iPad Air 3',
    'iPad Air 2',
    'iPad Air',
    'iPad Pro 13-inch (M5)',
    'iPad Pro 11-inch (M5)',
    'iPad Pro 13-inch (M4)',
    'iPad Pro 11-inch (M4)',
    'iPad Pro 12.9-inch (6th generation)',
    'iPad Pro 11-inch (4th generation)',
    'iPad Pro 12.9-inch (5th generation)',
    'iPad Pro 11-inch (3rd generation)',
    'iPad Pro 12.9-inch (4th generation)',
    'iPad Pro 11-inch (2nd generation)',
    'iPad Pro 12.9-inch (3rd generation)',
    'iPad Pro 11-inch',
    'iPad Pro 12.9-inch',
    'iPad Pro 10.5-inch',
    'iPad Pro 9.7-inch',
    'iPad mini (A17 Pro)',
    'iPad mini 6',
    'iPad mini 5',
    'iPad mini 4',
    'iPad mini 3',
    'iPad mini 2',
    'iPad mini',
    'Other',
  ],
  Lenovo: [
    'Lenovo Idea Tab',
    'Lenovo Idea Tab Pro',
    'Lenovo Idea Tab Plus',
    'Lenovo Tab',
    'Lenovo Tab One',
    'Lenovo Tab K9',
    'Lenovo Tab K11',
    'Lenovo Tab K11 Gen 2',
    'Lenovo Tab M8',
    'Lenovo Tab M9',
    'Lenovo Tab M10',
    'Lenovo Tab M10 Plus',
    'Lenovo Tab M11',
    'Lenovo Tab P11',
    'Lenovo Tab P11 Plus',
    'Lenovo Tab P11 Pro',
    'Lenovo Tab P12',
    'Lenovo Tab P12 Pro',
    'Lenovo Tab Extreme',
    'Lenovo Yoga Tab 11',
    'Lenovo Yoga Tab 13',
    'Lenovo Yoga Tab Plus',
    'Lenovo Yoga Smart Tab',
    'Lenovo Legion Tab',
    'Lenovo Legion Y700',
    'Lenovo Legion Y700 2023',
    'Lenovo Legion Y700 2025',
    'Lenovo Legion Y700 Gen 4',
    'Lenovo Legion Y700 Gen 5',
    'Other',
  ],
  Huawei: [
    'MatePad',
    'MatePad SE',
    'MatePad SE 10.4',
    'MatePad SE 11',
    'MatePad 10.4',
    'MatePad 11',
    'MatePad 11.5',
    'MatePad 11.5 2025',
    'MatePad 11.5 S',
    'MatePad 11.5 S 2025',
    'MatePad 12 X',
    'MatePad 12 X 2025',
    'MatePad Air',
    'MatePad Air 2025',
    'MatePad Pro 10.8',
    'MatePad Pro 11',
    'MatePad Pro 12.2',
    'MatePad Pro 13.2',
    'MatePad Pro 13.2 2024',
    'MatePad Edge',
    'Other',
  ],
  Xiaomi: [
    'Xiaomi Pad 7',
    'Xiaomi Pad 7 Pro',
    'Xiaomi Pad 7S Pro',
    'Xiaomi Pad 7 Ultra',
    'Xiaomi Pad 6',
    'Xiaomi Pad 6 Pro',
    'Xiaomi Pad 6S Pro',
    'Xiaomi Pad 5',
    'Xiaomi Pad 5 Pro',
    'Xiaomi Pad 5 Pro 12.4',
    'Xiaomi Pad 4',
    'Xiaomi Pad 4 Plus',
    'Xiaomi Pad 3',
    'Xiaomi Pad 2',
    'Xiaomi Pad 1',
    'Redmi Pad',
    'Redmi Pad SE',
    'Redmi Pad SE 8.7',
    'Redmi Pad 2',
    'Redmi Pad 2 SE',
    'Redmi Pad 2 Pro',
    'Redmi Pad Pro',
    'Redmi K Pad',
    'Black Shark Pad',
    'Black Shark Pad 2',
    'Black Shark Pad 5',
    'Black Shark Pad 6',
    'Black Shark Pad 7',
    'Black Shark Pad 7 Pro',
    'Other',
  ],
  Honor: [
    'Honor Pad',
    'Honor Pad X8',
    'Honor Pad X8a',
    'Honor Pad X8b',
    'Honor Pad X9',
    'Honor Pad X9a',
    'Honor Pad X9 Pro',
    'Honor Pad 9',
    'Honor Pad 9 Pro',
    'Honor Pad V7',
    'Honor Pad V8',
    'Honor Pad V9',
    'Honor Pad GT',
    'Honor Pad GT Pro',
    'Honor MagicPad 2',
    'Honor MagicPad 3',
    'Honor MagicPad 3 Pro',
    'Honor MagicPad 4',
    'Other',
  ],
  Amazon: [
    'Fire 7',
    'Fire HD 8',
    'Fire HD 8 Plus',
    'Fire HD 10',
    'Fire HD 10 Plus',
    'Fire Max 11',
    'Fire HD 10 Kids',
    'Fire HD 10 Kids Pro',
    'Fire HD 8 Kids',
    'Fire HD 8 Kids Pro',
    'Other',
  ],
  Microsoft: [
    'Surface Go',
    'Surface Go 2',
    'Surface Go 3',
    'Surface Go 4',
    'Surface Pro',
    'Surface Pro 3',
    'Surface Pro 4',
    'Surface Pro 5',
    'Surface Pro 6',
    'Surface Pro 7',
    'Surface Pro 7+',
    'Surface Pro 8',
    'Surface Pro 9',
    'Surface Pro 10',
    'Surface Pro 11',
    'Surface Pro X',
    'Surface Book',
    'Surface Book 2',
    'Surface Book 3',
    'Other',
  ],
  Tecno: [
    'Tecno MegaPad 10',
    'Tecno MegaPad 11',
    'Tecno MegaPad 12',
    'Tecno MegaPad SE',
    'Tecno MegaPad Pro',
    'Tecno MegaPad 2',
    'Other',
  ],
  OnePlus: [
    'OnePlus Pad',
    'OnePlus Pad Go',
    'OnePlus Pad Go 2',
    'OnePlus Pad 2',
    'OnePlus Pad 3',
    'Other',
  ],
  Oppo: [
    'Oppo Pad',
    'Oppo Pad Air',
    'Oppo Pad 2',
    'Oppo Pad 3',
    'Oppo Pad 3 Pro',
    'Oppo Pad Neo',
    'Oppo Pad SE',
    'Other',
  ],
  Realme: [
    'Realme Pad',
    'Realme Pad Mini',
    'Realme Pad 2',
    'Realme Pad 2 Lite',
    'Realme Pad X',
    'Realme Pad 2 5G',
    'Other',
  ],
  TCL: [
    'TCL Tab 8',
    'TCL Tab 8 LE',
    'TCL Tab 10',
    'TCL Tab 10L',
    'TCL Tab 10s',
    'TCL Tab 10 Gen 2',
    'TCL Tab 11',
    'TCL Tab 11 FE',
    'TCL Tab 12',
    'TCL NXTPAPER 10s',
    'TCL NXTPAPER 11',
    'TCL NXTPAPER 11 Plus',
    'Other',
  ],
  Asus: [
    'ASUS ROG Flow Z13',
    'ASUS ROG Flow Z13 2025',
    'ASUS ROG Tablet',
    'ASUS ZenPad 3S 10',
    'ASUS ZenPad 10',
    'ASUS ZenPad 8',
    'ASUS ZenPad 7',
    'ASUS Transformer Pad',
    'Other',
  ],
  Google: [
    'Google Pixel Tablet',
    'Google Pixel Tablet 2',
    'Other',
  ],
  Nokia: [
    'Nokia T20',
    'Nokia T21',
    'Nokia T10',
    'Nokia T10 LTE',
    'Other',
  ],
  Motorola: [
    'Moto Tab G20',
    'Moto Tab G20 LTE',
    'Moto Tab G62',
    'Moto Tab G70',
    'Moto Tab G70 LTE',
    'Moto Tab G84',
    'Moto Tab 2024',
    'Moto Pad 60',
    'Moto Pad 60 Pro',
    'Moto Pad 70',
    'Moto Pad 2026',
    'Other',
  ],
  itel: [
    'itel Pad 1',
    'itel Pad 2',
    'itel VistaTab 10',
    'itel VistaTab 10 Mini',
    'itel VistaTab 30',
    'itel VistaTab 30 Pro',
    'Other',
  ],
  Acer: [
    'Acer Iconia Tab',
    'Acer Iconia One',
    'Acer Iconia A1',
    'Acer Iconia B1',
    'Acer Iconia W3',
    'Acer Iconia W4',
    'Acer Iconia Tab 10',
    'Acer Iconia Tab 8',
    'Acer Iconia Duo',
    'Other',
  ],
  Alcatel: [
    'Alcatel 1T',
    'Alcatel 1T 7',
    'Alcatel 1T 10',
    'Alcatel 3T 8',
    'Alcatel 3T 10',
    'Alcatel 3T 10 4G',
    'Alcatel Joy Tab',
    'Alcatel Joy Tab 2',
    'Other',
  ],
  ZTE: [
    'ZTE AxonPad',
    'ZTE AxonPad 5G',
    'ZTE nubia Pad 3D',
    'ZTE nubia Pad 3D II',
    'ZTE Red Magic Gaming Tablet',
    'ZTE Blade Tab',
    'ZTE Grand Memo Pad',
    'Other',
  ],
  Vivo: [
    'Vivo Pad',
    'Vivo Pad Air',
    'Vivo Pad2',
    'Vivo Pad3',
    'Vivo Pad3 Pro',
    'Vivo Pad5',
    'Vivo Pad5 Pro',
    'Other',
  ],
  Cidea: ['Other'],
  Other: ['Other'],
};

// ---------- TV & Audio types ----------

export const TV_AUDIO_TYPES = [
  'TVs',
  'Projectors',
  'TV Receivers',
  'Media Players',
  'Decoders',
  'Digital Signage',
  'DVD Players',
  'Speakers',
  'Microphones',
  'Home Theater Systems',
  'Sound Systems',
  'Soundcards',
  'Amplifiers',
  'Music Mixers',
  'Radios',
  'Turntables',
  'Karaoke',
  'Other',
];

// ---------- Cameras: types and models ----------

export const CAMERA_TYPES = [
  'Digital Cameras',
  'DSLR Cameras',
  'Video Cameras',
  'Action Cameras',
  'Film Cameras',
  'Camera Lenses',
  'Drones',
  'Accessories',
];

export const CAMERA_MODELS: Record<string, string[]> = {
  Canon: [
    'EOS 1500D',
    'EOS 2000D',
    'EOS 4000D',
    'EOS 80D',
    'EOS 90D',
    'EOS 5D Mark IV',
    'EOS R',
    'EOS R6',
    'EOS M50',
    'Other',
  ],
  Sony: [
    'Alpha a6000',
    'Alpha a6400',
    'Alpha a7 III',
    'Alpha a7 IV',
    'ZV-E10',
    'ZV-1',
    'Handycam',
    'Other',
  ],
  Nikon: [
    'D3500',
    'D5600',
    'D7500',
    'D850',
    'Z50',
    'Z6 II',
    'Z fc',
    'Other',
  ],
  GoPro: [
    'Hero 9',
    'Hero 10',
    'Hero 11',
    'Hero 12',
    'Other',
  ],
  DJI: [
    'Osmo Action 3',
    'Osmo Pocket 2',
    'Mini 3',
    'Mavic 3',
    'Other',
  ],
  Fujifilm: [
    'X-T30',
    'X-S10',
    'Instax Mini',
    'Other',
  ],
  Panasonic: ['Lumix G7', 'Lumix GH5', 'Lumix S5', 'Other'],
  Lumix: ['G7', 'GH5', 'S5', 'FZ300', 'Other'],
  Olympus: ['OM-D E-M10', 'OM-D E-M5', 'PEN E-PL9', 'Other'],
  Pentax: ['K-70', 'K-3 III', 'KF', 'Other'],
  Leica: ['Q2', 'M10', 'D-Lux 7', 'Other'],
  Kodak: ['PixPro AZ401', 'Ektar H35', 'Other'],
  Polaroid: ['Now', 'OneStep', 'Other'],
  Sigma: ['18-35mm f/1.8', '50mm f/1.4', '24-70mm f/2.8', 'Other'],
  Yongnuo: ['YN50mm f/1.8', 'YN560 Flash', 'Other'],
  Vivitar: ['Other'],
  JVC: ['Other'],
  Xiaomi: ['Mi Action Camera 4K', 'Other'],
  Samsung: ['Other'],
  Other: ['Other'],
};

// ---------- Subcategory pictures ----------
// Pictures live in public/categories/sub/<slug>.jpg
// When you add a new picture, add its slug to this list.

const SUB_IMAGES = new Set([
  'phones',
  'computers-tablets',
  'tv-audio',
  'cameras',
  'gaming',

  'cars',
  'motorcycles',
  'trucks-vans',
  'parts-accessories',

  'sofas',
  'beds',
  'tables-chairs',
  'storage',
  'other-furniture',

  'men-s-clothing',
  'women-s-clothing',
  'shoes',
  'bags-accessories',
  'other-fashion',

  'for-rent',
  'land',
  'other-property',
]);

// "Men's Clothing" -> "men-s-clothing"
export function subcategorySlug(
  name: string,
): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Returns the picture path,
// or null if that subcategory has no picture yet
export function subcategoryImage(
  name: string,
): string | null {
  const raw = subcategorySlug(name);

  // Reuse existing pictures after renaming
  const aliases: Record<string, string> = {
    computers: 'computers-tablets',
    tv: 'tv-audio',
  };

  const slug = aliases[raw] ?? raw;

  return SUB_IMAGES.has(slug)
    ? `/categories/sub/${slug}.jpg`
    : null;
}


// ---------- Helpers ----------

// Models for a subcategory + brand (empty list = no models yet)
export function getModels(
  subcategory: string,
  brand: string,
): string[] {
  if (subcategory === 'Tablets') {
    return TABLET_MODELS[brand] ?? ['Other'];
  }
  if (subcategory === 'Cameras') {
    return CAMERA_MODELS[brand] ?? ['Other'];
  }
  return [];
}

// Extra brands shown after the buyer/seller taps "Other"
export function getOtherBrands(
  subcategory: string,
): string[] {
  return OTHER_BRANDS[subcategory] ?? [];
}